// 声優個人ページ（app/person/[name]/[year]/[season]/page.tsx）が表示する「代表作＋役名」を
// 人力で補完するデータ。Annict GraphQL APIには「声優→出演作品」の逆引きクエリが存在せず
// （Person型にcastsCount等はあるが作品一覧を返すフィールドが無い）、全出演作品を機械的に
// 集計しようとすると全クール分のAnnictデータを舐める必要がありAnnictへの負荷が大きい
// （docs/operations.mdの「⑪」、および[[annict-load-consideration]]の方針に反する）。
// そのため「今期の出演作品」はこれまでどおりAnnictのリアルタイムデータで自動表示し、
// 「代表作＋役名」だけをWikipedia等の一次情報から人力で確認・追記する運用にした
// （content/works/{id}.json の人力コンテンツと同じ思想）。
//
// キーはAnnictのcasts.nameと完全一致させる（app/person/[name]/... のnameパラメータと同じ文字列）。
export interface PersonFilmographyEntry {
  works: { title: string; character: string }[];
  // 出典（Wikipedia記事等）のURL。CLAUDE.mdの「一次情報のみ・出典明示」方針に従い必須とする。
  sourceUrl: string;
  // 確認日（"YYYY-MM-DD"）。データが古くなっていないかの目安。
  confirmedDate: string;
}

export const PERSON_FILMOGRAPHY: Record<string, PersonFilmographyEntry> = {
  豊口めぐみ: {
    sourceUrl: "https://ja.wikipedia.org/wiki/豊口めぐみ",
    confirmedDate: "2026-07-13",
    works: [
      { title: "アリスSOS", character: "アリス" },
      { title: "デュアル！ぱられルンルン物語", character: "羅螺みつき / ミス・ラー" },
      { title: "超GALS！寿蘭", character: "寿蘭" },
      { title: "ポケットモンスター ダイヤモンド&パール", character: "ヒカリ" },
      { title: "鋼の錬金術師", character: "ウィンリィ・ロックベル" },
      { title: "マリア様がみてる", character: "佐藤聖" },
      { title: "いちご100%", character: "西野つかさ" },
      { title: "BLACK LAGOON", character: "レヴィ" },
      { title: "マクロスF", character: "クラン・クラン" },
      { title: "スイートプリキュア♪", character: "黒川エレン / キュアビート" },
      { title: "IS〈インフィニット・ストラトス〉", character: "織斑千冬" },
      { title: "Fate/Zero", character: "ソラウ・ヌァザレ・ソフィアリ" },
      { title: "ダンガンロンパ", character: "江ノ島盾子" },
      { title: "転生したらスライムだった件", character: "大賢者 / 智慧之王" },
      { title: "ウマ娘 プリティーダービー", character: "東条ハナ" },
    ],
  },
  早見沙織: {
    sourceUrl: "https://ja.wikipedia.org/wiki/早見沙織",
    confirmedDate: "2026-07-14",
    works: [
      { title: "俺の妹がこんなに可愛いわけがない", character: "新垣あやせ" },
      { title: "あの日見た花の名前を僕達はまだ知らない。", character: "鶴見知利子（つるこ）" },
      { title: "やはり俺の青春ラブコメはまちがっている。", character: "雪ノ下雪乃" },
      { title: "アイドルマスター シンデレラガールズ", character: "高垣楓" },
      { title: "魔法科高校の劣等生", character: "司波深雪" },
      { title: "魔法つかいプリキュア！", character: "花海ことは／キュアフェリーチェ" },
      { title: "鬼滅の刃", character: "胡蝶しのぶ" },
      { title: "SPY×FAMILY", character: "ヨル・フォージャー" },
      { title: "そらのおとしもの", character: "イカロス" },
      { title: "セキレイ", character: "結" },
      { title: "ワンパンマン", character: "地獄のフブキ" },
      { title: "賭ケグルイ", character: "蛇喰夢子" },
    ],
  },
  関根明良: {
    sourceUrl: "https://ja.wikipedia.org/wiki/関根明良",
    confirmedDate: "2026-07-14",
    works: [
      { title: "プリンセス・プリンシパル", character: "プリンセス" },
      { title: "アイカツ！", character: "藤原みやび" },
      { title: "魔法少女特殊戦あすか", character: "夢源くるみ" },
      { title: "旗揚！けものみち", character: "シグレ" },
      { title: "神之塔 -Tower of God-", character: "アナク・ザハード" },
      { title: "その着せ替え人形は恋をする", character: "山内瑠音" },
      { title: "明日ちゃんのセーラー服", character: "谷川景" },
      { title: "BIRDIE WING -Golf Girls' Story-", character: "リリィ・リップマン" },
      { title: "ひろがるスカイ！プリキュア", character: "ソラ・ハレワタール／キュアスカイ" },
      { title: "先輩はおとこのこ", character: "蒼井咲" },
      { title: "杖と剣のウィストリア", character: "エルファリア・アルヴィス・セルフォルト" },
    ],
  },
  阿座上洋平: {
    sourceUrl: "https://ja.wikipedia.org/wiki/阿座上洋平",
    confirmedDate: "2026-07-14",
    works: [
      { title: "クロムクロ", character: "青馬剣之介時貞" },
      { title: "ピアシェ〜私のイタリアン〜", character: "近野桐秀" },
      { title: "ようこそ実力至上主義の教室へ", character: "橋本正義" },
      { title: "新サクラ大戦 the Animation", character: "神山誠十郎" },
      { title: "ゴジラ S.P〈シンギュラポイント〉", character: "佐藤隼也" },
      { title: "白い砂のアクアトープ", character: "屋嘉間志空也" },
      { title: "D_CIDE TRAUMEREI THE ANIMATION", character: "織田龍平" },
      { title: "ラブオールプレー", character: "榊翔平" },
      { title: "それでも歩は寄せてくる", character: "田中歩" },
      { title: "虫かぶり姫", character: "アーヴィン・オランザ" },
      { title: "機動戦士ガンダム 水星の魔女", character: "グエル・ジェターク" },
      { title: "鴨乃橋ロンの禁断推理", character: "鴨乃橋ロン" },
      { title: "青のミブロ", character: "土方歳三" },
    ],
  },
  安済知佳: {
    sourceUrl: "https://ja.wikipedia.org/wiki/安済知佳",
    confirmedDate: "2026-07-14",
    works: [
      { title: "あにゃまる探偵 キルミンずぅ", character: "御子神ナギサ" },
      { title: "棺姫のチャイカ", character: "チャイカ・トラバント" },
      { title: "響け！ユーフォニアム", character: "高坂麗奈" },
      { title: "クズの本懐", character: "安楽岡花火" },
      { title: "灰と幻想のグリムガル", character: "メリイ" },
      { title: "同居人はひざ、時々、頭のうえ。", character: "押守なな" },
      { title: "地縛少年花子くん", character: "七峰桜" },
      { title: "リコリス・リコイル", character: "錦木千束" },
      { title: "進撃の巨人", character: "ミーナ・カロライナ" },
      { title: "SSSS.DYNAZENON", character: "飛鳥川ちせ" },
      { title: "ぐらんぶる", character: "古手川千紗" },
    ],
  },
  石川由依: {
    sourceUrl: "https://ja.wikipedia.org/wiki/石川由依",
    confirmedDate: "2026-07-14",
    works: [
      { title: "進撃の巨人", character: "ミカサ・アッカーマン" },
      { title: "ヴァイオレット・エヴァーガーデン", character: "ヴァイオレット・エヴァーガーデン" },
      { title: "トロピカル〜ジュ！プリキュア", character: "一之瀬みのり／キュアパパイア" },
      { title: "アイカツ！", character: "新条ひなき" },
      { title: "ガンダムビルドファイターズ", character: "コウサカ・チナ" },
      { title: "エロマンガ先生", character: "高砂智恵" },
      { title: "蒼穹のファフナー EXODUS", character: "水鏡美三香" },
      { title: "クオリディア・コード", character: "宇多良カナリア" },
      { title: "ガーリッシュ ナンバー", character: "片倉京" },
      { title: "けものフレンズ2", character: "キュルル" },
      { title: "聖女の魔力は万能です", character: "セイ／小鳥遊聖" },
      { title: "NieR:Automata Ver1.1a", character: "2B" },
    ],
  },
  水瀬いのり: {
    sourceUrl: "https://ja.wikipedia.org/wiki/水瀬いのり",
    confirmedDate: "2026-07-14",
    works: [
      { title: "ご注文はうさぎですか？", character: "香風智乃（チノ）" },
      { title: "心が叫びたがってるんだ。", character: "成瀬順" },
      { title: "ダンジョンに出会いを求めるのは間違っているだろうか", character: "ヘスティア" },
      { title: "Re:ゼロから始める異世界生活", character: "レム" },
      { title: "五等分の花嫁", character: "中野五月" },
      { title: "がっこうぐらし！", character: "丈槍由紀" },
      { title: "戦姫絶唱シンフォギア", character: "キャロル・マールス・ディーンハイム" },
      { title: "恋愛ラボ", character: "棚橋鈴音" },
      { title: "ViVid Strike!", character: "フーカ・レヴェントン" },
      { title: "少女終末旅行", character: "チト" },
      { title: "宇宙よりも遠い場所", character: "玉木マリ" },
      { title: "政宗くんのリベンジ", character: "小岩井吉乃" },
      { title: "キラキラ☆プリキュアアラモード", character: "キラ星シエル／キュアパルフェ" },
      { title: "青春ブタ野郎シリーズ", character: "牧之原翔子" },
    ],
  },
  東山奈央: {
    sourceUrl: "https://ja.wikipedia.org/wiki/東山奈央",
    confirmedDate: "2026-07-14",
    works: [
      { title: "神のみぞ知るセカイ", character: "中川かのん" },
      { title: "異国迷路のクロワーゼ The Animation", character: "湯音" },
      { title: "戦姫絶唱シンフォギア", character: "寺島詩織" },
      { title: "咲-Saki- 阿知賀編", character: "新子憧" },
      { title: "ラブライブ！", character: "高坂雪穂" },
      { title: "やはり俺の青春ラブコメはまちがっている。", character: "由比ヶ浜結衣" },
      { title: "きんいろモザイク", character: "九条カレン" },
      { title: "蒼き鋼のアルペジオ", character: "八月一日静" },
      { title: "ニセコイ", character: "桐崎千棘" },
      { title: "マクロスΔ", character: "レイナ・プラウラー" },
      { title: "ゆるキャン△", character: "志摩リン" },
      { title: "響け！ユーフォニアム", character: "傘木希美" },
      { title: "彼女、お借りします", character: "更科瑠夏" },
    ],
  },
  "M・A・O": {
    sourceUrl: "https://ja.wikipedia.org/wiki/M・A・O",
    confirmedDate: "2026-07-14",
    works: [
      { title: "クッキンアイドル アイ！マイ！まいん！", character: "キラキラ" },
      { title: "帰宅部活動記録", character: "あざらし" },
      { title: "サムライフラメンコ", character: "三澤瑞希" },
      { title: "DD北斗の拳", character: "リン" },
      { title: "愛・天地無用！", character: "沙流葉七" },
      { title: "俺、ツインテールになります。", character: "桜川尊" },
      { title: "極黒のブリュンヒルデ", character: "カズミ＝シュリーレンツァウアー" },
      { title: "がっこうぐらし！", character: "若狭悠里" },
      { title: "機動戦士ガンダム 鉄血のオルフェンズ", character: "ジュリエッタ・ジュリス" },
      { title: "クラシカロイド", character: "バダジェフスカ" },
      { title: "競女!!!!!!!!", character: "宮田さやか" },
      { title: "クロムクロ", character: "白羽由希奈" },
      { title: "転生したらスライムだった件", character: "シオン" },
      { title: "ようこそ実力至上主義の教室へ", character: "佐倉愛里" },
      { title: "からかい上手の高木さん", character: "天川ユカリ" },
      { title: "炎炎ノ消防隊", character: "アイリス" },
    ],
  },
  戸松遥: {
    sourceUrl: "https://ja.wikipedia.org/wiki/戸松遥",
    confirmedDate: "2026-07-14",
    works: [
      { title: "あの日見た花の名前を僕達はまだ知らない。", character: "安城鳴子（あなる）" },
      { title: "ソードアート・オンライン", character: "アスナ／結城明日奈" },
      { title: "ハピネスチャージプリキュア！", character: "氷川いおな／キュアフォーチュン" },
      { title: "妖怪ウォッチ", character: "ケータ／天野景太" },
      { title: "かんなぎ", character: "ナギ" },
      { title: "絶対可憐チルドレン", character: "三宮紫穂" },
      { title: "To LOVEる -とらぶる-", character: "ララ・サタリン・デビルーク" },
      { title: "神曲奏界ポリフォニカ", character: "コーティカルテ・アパ・ラグランジェス" },
      { title: "ダーリン・イン・ザ・フランキス", character: "ゼロツー" },
      { title: "ヴァイオレット・エヴァーガーデン", character: "アイリス・カナリー" },
    ],
  },
  大塚芳忠: {
    sourceUrl: "https://ja.wikipedia.org/wiki/大塚芳忠",
    confirmedDate: "2026-07-14",
    works: [
      { title: "機動戦士Ζガンダム", character: "ヤザン・ゲーブル" },
      { title: "機甲戦記ドラグナー", character: "タップ・オセアノ" },
      { title: "機動武闘伝Gガンダム", character: "チボデー・クロケット" },
      { title: "∀ガンダム", character: "ギャバン・グーニー" },
      { title: "最遊記シリーズ", character: "你健一／烏哭三蔵" },
      { title: "NARUTO -ナルト-", character: "自来也" },
      { title: "銀魂", character: "阿伏兎" },
      { title: "幼女戦記", character: "ゼートゥーア" },
      { title: "ゴールデンカムイ", character: "鶴見中尉" },
      { title: "転生したらスライムだった件", character: "ハクロウ" },
      { title: "亜人", character: "佐藤" },
      { title: "文豪ストレイドッグス", character: "夏目漱石" },
      { title: "バキ", character: "ビスケット・オリバ" },
    ],
  },
  高橋李依: {
    sourceUrl: "https://ja.wikipedia.org/wiki/高橋李依",
    confirmedDate: "2026-07-14",
    works: [
      { title: "この素晴らしい世界に祝福を！", character: "めぐみん" },
      { title: "Re:ゼロから始める異世界生活", character: "エミリア" },
      { title: "魔法つかいプリキュア！", character: "朝日奈みらい／キュアミラクル" },
      { title: "【推しの子】", character: "アイ" },
      { title: "それが声優！", character: "一ノ瀬双葉" },
      { title: "からかい上手の高木さん", character: "高木さん" },
      { title: "ゆるキャン△", character: "斉藤恵那" },
      { title: "Fate/Grand Order", character: "マシュ・キリエライト（2代目）" },
      { title: "がっこうぐらし！", character: "直樹美紀" },
      { title: "彼女、お借りします", character: "桜沢墨" },
      { title: "地獄楽", character: "杠" },
    ],
  },
  日高里菜: {
    sourceUrl: "https://ja.wikipedia.org/wiki/日高里菜",
    confirmedDate: "2026-07-14",
    works: [
      { title: "とある魔術の禁書目録", character: "打ち止め〈ラストオーダー〉" },
      { title: "ソードアート・オンライン", character: "シリカ／綾野珪子" },
      { title: "ロウきゅーぶ！", character: "香椎愛莉" },
      { title: "アクセル・ワールド", character: "ニコ〈上月由仁子／スカーレット・レイン〉" },
      { title: "転生したらスライムだった件", character: "ミリム" },
      { title: "盾の勇者の成り上がり", character: "フィーロ" },
      { title: "ようこそ実力至上主義の教室へ", character: "坂柳有栖" },
      { title: "戦姫絶唱シンフォギアAXZ", character: "プレラーティ" },
      { title: "艦隊これくしょん -艦これ-", character: "睦月" },
      { title: "トロピカル〜ジュ！プリキュア", character: "ローラ／キュアラメール" },
    ],
  },
  内山昂輝: {
    sourceUrl: "https://ja.wikipedia.org/wiki/内山昂輝",
    confirmedDate: "2026-07-14",
    works: [
      { title: "キングダム ハーツ シリーズ", character: "ロクサス／ヴェントゥス" },
      { title: "機動戦士ガンダムUC", character: "バナージ・リンクス" },
      { title: "ピンポン THE ANIMATION", character: "スマイル／月本誠" },
      { title: "DEVILMAN crybaby", character: "不動明" },
      { title: "僕のヒーローアカデミア", character: "死柄木弔" },
      { title: "ハイキュー!!", character: "月島蛍" },
      { title: "呪術廻戦", character: "狗巻棘" },
      { title: "ソウルイーター", character: "ソウル＝イーター" },
      { title: "屍鬼", character: "結城夏野" },
      { title: "ニセコイ", character: "一条楽" },
      { title: "Charlotte", character: "乙坂有宇" },
      { title: "ユーリ!!! on ICE", character: "ユーリ・プリセツキー" },
      { title: "ホリミヤ", character: "宮村伊澄" },
    ],
  },
  安元洋貴: {
    sourceUrl: "https://ja.wikipedia.org/wiki/安元洋貴",
    confirmedDate: "2026-07-14",
    works: [
      { title: "BLEACH", character: "茶渡泰虎" },
      { title: "鬼灯の冷徹", character: "鬼灯" },
      { title: "弱虫ペダル", character: "金城真護" },
      { title: "ヘタリア Axis Powers", character: "ドイツ" },
      { title: "ソードアート・オンライン", character: "エギル" },
      { title: "FAIRY TAIL", character: "エルフマン・ストラウス" },
      { title: "ワンパンマン", character: "キング" },
      { title: "黒執事", character: "アグニ" },
      { title: "この素晴らしい世界に祝福を！", character: "デュラハン" },
      { title: "ドルアーガの塔", character: "ウトゥ" },
      { title: "食戟のソーマ", character: "美作昴" },
      { title: "ユーリ!!! on ICE", character: "クリストフ・ジャコメッティ" },
    ],
  },
  小清水亜美: {
    sourceUrl: "https://ja.wikipedia.org/wiki/小清水亜美",
    confirmedDate: "2026-07-14",
    works: [
      { title: "明日のナージャ", character: "ナージャ・アップルフィールド" },
      { title: "スクールランブル", character: "塚本天満" },
      { title: "おねがいマイメロディ", character: "桜塚美紀" },
      { title: "交響詩篇エウレカセブン", character: "アネモネ" },
      { title: "狼と香辛料", character: "ホロ" },
      { title: "コードギアス 反逆のルルーシュ", character: "紅月カレン" },
      { title: "スイートプリキュア♪", character: "北条響／キュアメロディ" },
      { title: "ストライクウィッチーズ", character: "シャーロット・E・イェーガー" },
      { title: "Persona4 the ANIMATION", character: "天城雪子" },
      { title: "キルラキル", character: "纏流子" },
    ],
  },
  本渡楓: {
    sourceUrl: "https://ja.wikipedia.org/wiki/本渡楓",
    confirmedDate: "2026-07-14",
    works: [
      { title: "かみさまみならい ヒミツのここたま", character: "四葉こころ" },
      { title: "不思議なソメラちゃん", character: "野乃本ククル" },
      { title: "レガリア The Three Sacred Stars", character: "ユインシエル・アステリア" },
      { title: "競女!!!!!!!!", character: "青葉風音" },
      { title: "ガーリッシュナンバー", character: "久我山八重" },
      { title: "うらら迷路帖", character: "巽紺" },
      { title: "亜人ちゃんは語りたい", character: "小鳥遊ひかり" },
      { title: "バトルガール ハイスクール", character: "煌上花音" },
      { title: "アニメガタリズ", character: "阿佐ヶ谷未乃愛" },
      { title: "こみっくがーるず", character: "恋塚小夢" },
      { title: "ヒナまつり", character: "三嶋瞳" },
      { title: "ちおちゃんの通学路", character: "細川雪" },
      { title: "ゾンビランドサガ", character: "源さくら" },
      { title: "色づく世界の明日から", character: "月白琥珀" },
      { title: "刀使ノ巫女", character: "衛藤可奈美" },
      { title: "魔女の旅々", character: "イレイナ" },
    ],
  },
  長縄まりあ: {
    sourceUrl: "https://ja.wikipedia.org/wiki/長縄まりあ",
    confirmedDate: "2026-07-14",
    works: [
      { title: "小林さんちのメイドラゴン", character: "カンナ／カンナカムイ" },
      { title: "はたらく細胞", character: "血小板" },
      { title: "スロウスタート", character: "千石冠" },
      { title: "ステラのまほう", character: "本田珠輝" },
      { title: "女子高生の無駄づかい", character: "ロリ／百井咲久" },
      { title: "アズールレーン", character: "ラフィー" },
      { title: "BNA ビー・エヌ・エー", character: "日渡なずな" },
      { title: "わんだふるぷりきゅあ！", character: "犬飼こむぎ／キュアワンダフル" },
      { title: "君のことが大大大大大好きな100人の彼女", character: "好本静" },
      { title: "ワールドダイスター", character: "新妻八恵" },
      { title: "六畳間の侵略者!?", character: "ティアミリス・グレ・フォルトーゼ" },
      { title: "奇異太郎少年の妖怪絵日記", character: "雪娘" },
      { title: "異世界薬局", character: "ブランシュ・ド・メディシス" },
    ],
  },
  村瀬歩: {
    sourceUrl: "https://ja.wikipedia.org/wiki/村瀬歩",
    confirmedDate: "2026-07-14",
    works: [
      { title: "ハイキュー!!", character: "日向翔陽" },
      { title: "新世界より", character: "青沼瞬（14歳）" },
      { title: "ブラッククローバー", character: "ラック・ボルティア" },
      { title: "魔入りました！入間くん", character: "鈴木入間" },
      { title: "Dr.STONE", character: "銀狼" },
      { title: "王様ランキング", character: "カゲ" },
      { title: "かくしごと", character: "芥子駆" },
      { title: "あんさんぶるスターズ!", character: "姫宮桃李" },
      { title: "ひろがるスカイ！プリキュア", character: "夕凪ツバサ／キュアウィング" },
      { title: "さらざんまい", character: "矢逆一稀" },
      { title: "ダイヤのA", character: "由井薫" },
    ],
  },
  子安武人: {
    sourceUrl: "https://ja.wikipedia.org/wiki/子安武人",
    confirmedDate: "2026-07-14",
    works: [
      { title: "天空戦記シュラト", character: "夜叉王ガイ" },
      { title: "楽しいムーミン一家", character: "スナフキン" },
      { title: "宇宙の騎士テッカマンブレード", character: "テッカマン・エビル／相羽シンヤ" },
      { title: "ビーストウォーズ 超生命体トランスフォーマー", character: "コンボイ" },
      { title: "新機動戦記ガンダムW", character: "ゼクス・マーキス" },
      { title: "ふしぎ遊戯", character: "星宿" },
      { title: "スレイヤーズ", character: "赤法師レゾ" },
      { title: "新世紀エヴァンゲリオン", character: "青葉シゲル" },
      { title: "少女革命ウテナ", character: "桐生冬芽" },
      { title: "頭文字D", character: "高橋涼介" },
      { title: "∀ガンダム", character: "ギム・ギンガナム" },
      { title: "機動戦士ガンダムSEED", character: "ムウ・ラ・フラガ" },
      { title: "銀魂", character: "高杉晋助" },
      { title: "進撃の巨人", character: "ジーク（獣の巨人）" },
      { title: "Re:ゼロから始める異世界生活", character: "ロズワール" },
    ],
  },
  ファイルーズあい: {
    sourceUrl: "https://ja.wikipedia.org/wiki/ファイルーズあい",
    confirmedDate: "2026-07-14",
    works: [
      { title: "ダンベル何キロ持てる?", character: "紗倉ひびき" },
      { title: "推しが武道館いってくれたら死ぬ", character: "えりぴよ" },
      { title: "神田川JET GIRLS", character: "エミリー・オレンジ" },
      { title: "トロピカル〜ジュ！プリキュア", character: "夏海まなつ／キュアサマー" },
      { title: "ジョジョの奇妙な冒険 ストーンオーシャン", character: "空条徐倫" },
      { title: "チェンソーマン", character: "パワー" },
      { title: "陰の実力者になりたくて！", character: "デルタ" },
      { title: "悪役令嬢レベル99", character: "ユミエラ・ドルクネス" },
      { title: "怪獣8号", character: "四ノ宮キコル" },
    ],
  },
  白石晴香: {
    sourceUrl: "https://ja.wikipedia.org/wiki/白石晴香",
    confirmedDate: "2026-07-14",
    works: [
      { title: "コクリコ坂から", character: "松崎空" },
      { title: "ガラスの仮面ですがZ", character: "姫川亜弓" },
      { title: "干物妹！うまるちゃん", character: "本場切絵" },
      { title: "あんハピ♪", character: "雲雀丘瑠璃" },
      { title: "山賊の娘ローニャ", character: "ローニャ" },
      { title: "ゴールデンカムイ", character: "アシㇼパ" },
      { title: "うちのメイドがウザすぎる！", character: "高梨ミーシャ" },
      { title: "アニマエール！", character: "牛久花和" },
      { title: "ぼくたちは勉強ができない", character: "古橋文乃" },
      { title: "俺を好きなのはお前だけかよ", character: "ひまわり（日向葵）" },
      { title: "アクションヒロイン チアフルーツ", character: "紫村果音" },
      { title: "セントールの悩み", character: "名楽羌子" },
      { title: "転生したらスライムだった件", character: "アリス" },
      { title: "ラブライブ!スーパースター!!", character: "ココノ" },
      { title: "明日ちゃんのセーラー服", character: "戸鹿野舞衣" },
    ],
  },
  日笠陽子: {
    sourceUrl: "https://ja.wikipedia.org/wiki/日笠陽子",
    confirmedDate: "2026-07-14",
    works: [
      { title: "けいおん!", character: "秋山澪" },
      { title: "キングダム", character: "羌瘣" },
      { title: "はたらく魔王さま!", character: "遊佐恵美" },
      { title: "戦姫絶唱シンフォギア", character: "マリア・カデンツァヴナ・イヴ" },
      { title: "SHAMAN KING", character: "麻倉葉" },
      { title: "ハイスクールD×D", character: "リアス・グレモリー" },
      { title: "IS〈インフィニット・ストラトス〉", character: "篠ノ之箒" },
      { title: "これはゾンビですか?", character: "セラ" },
      { title: "生徒会役員共", character: "天草シノ" },
      { title: "ダンガンロンパ", character: "霧切響子" },
      { title: "ヤマノススメ", character: "斎藤楓" },
      { title: "BanG Dream!", character: "宇田川巴" },
      { title: "ありふれた職業で世界最強", character: "ティオ・クラルス" },
      { title: "Dr.STONE", character: "北東西南" },
    ],
  },
  田村ゆかり: {
    sourceUrl: "https://ja.wikipedia.org/wiki/田村ゆかり",
    confirmedDate: "2026-07-14",
    works: [
      { title: "ひぐらしのなく頃に", character: "古手梨花" },
      { title: "極上生徒会", character: "蘭堂りの／プッチャン" },
      { title: "魔法少女リリカルなのは", character: "高町なのは" },
      { title: "ギャラクシーエンジェル", character: "蘭花・フランボワーズ" },
      { title: "D.C. 〜ダ・カーポ〜", character: "芳乃さくら" },
      { title: "スクライド", character: "由詑かなみ" },
      { title: "Kanon", character: "川澄舞" },
      { title: "NARUTO -ナルト-", character: "テンテン" },
      { title: "黒執事", character: "エリザベス・エセル・コーディリア・ミッドフォード" },
      { title: "灼眼のシャナ", character: "ティリエル" },
      { title: "かしまし〜ガール・ミーツ・ガール〜", character: "来栖とまり" },
      { title: "HUGっと！プリキュア", character: "ルールー・アムール／キュアアムール" },
    ],
  },
  榎木淳弥: {
    sourceUrl: "https://ja.wikipedia.org/wiki/榎木淳弥",
    confirmedDate: "2026-07-14",
    works: [
      { title: "呪術廻戦", character: "虎杖悠仁" },
      { title: "ジョジョの奇妙な冒険 黄金の風", character: "パンナコッタ・フーゴ" },
      { title: "BEASTARS", character: "ジャック" },
      { title: "ベイブレードバースト", character: "紅シュウ" },
      { title: "風が強く吹いている", character: "城太郎（ジョータ）" },
      { title: "アイドルマスター SideM", character: "舞田類" },
      { title: "ID:INVADED イド:インヴェイデッド", character: "若鹿一雄" },
      { title: "トニカクカワイイ", character: "由崎星空" },
      { title: "はたらく細胞BLACK", character: "赤血球" },
      { title: "八男って、それはないでしょう!", character: "ヴェンデリン" },
      { title: "活撃 刀剣乱舞", character: "堀川国広" },
      { title: "ブギーポップは笑わない", character: "早乙女正美" },
      { title: "刀剣乱舞-花丸-", character: "堀川国広" },
      { title: "カードファイト!! ヴァンガード", character: "綺場シオン" },
      { title: "東京リベンジャーズ", character: "乾青宗" },
    ],
  },
  梅原裕一郎: {
    sourceUrl: "https://ja.wikipedia.org/wiki/梅原裕一郎",
    confirmedDate: "2026-07-14",
    works: [
      { title: "美男高校地球防衛部LOVE!", character: "由布院煙" },
      { title: "終わりのセラフ", character: "レーネ・シム" },
      { title: "アクエリオンロゴス", character: "空篠翼人" },
      { title: "ガッチャマン クラウズ インサイト", character: "鈴木理詰夢" },
      { title: "赤髪の白雪姫", character: "ミツヒデ" },
      { title: "ミリオンドール", character: "リュウサン" },
      { title: "ヤングブラック・ジャック", character: "間黒男" },
      { title: "機動戦士ガンダム 鉄血のオルフェンズ", character: "ユージン・セブンスターク" },
      { title: "タイガーマスクW", character: "藤井タクマ／タイガー・ザ・ダーク" },
      { title: "ようこそ実力至上主義の教室へ", character: "堀北学" },
      { title: "キャプテン翼", character: "若島津健" },
      { title: "ゴブリンスレイヤー", character: "ゴブリンスレイヤー" },
      { title: "あんさんぶるスターズ!", character: "蓮巳敬人" },
      { title: "鬼滅の刃 刀鍛冶の里編", character: "積怒" },
    ],
  },
  坂泰斗: {
    sourceUrl: "https://ja.wikipedia.org/wiki/坂泰斗",
    confirmedDate: "2026-07-14",
    works: [
      { title: "魔術士オーフェンはぐれ旅", character: "ハーティア" },
      { title: "美少年探偵団", character: "咲口長広" },
      { title: "お隣の天使様にいつの間にか駄目人間にされていた件", character: "藤宮周" },
      { title: "俺だけレベルアップな件", character: "水篠旬" },
      { title: "VAZZROCK THE ANIMATION", character: "立花歩" },
      { title: "転生貴族、鑑定スキルで成り上がる", character: "リーツ・ミューセス" },
      { title: "妖怪学校の先生はじめました!", character: "泥田耕太郎" },
      { title: "SYNDUALITY Noir", character: "マハト〈黒仮面〉" },
    ],
  },
  榊原優希: {
    sourceUrl: "https://ja.wikipedia.org/wiki/榊原優希",
    confirmedDate: "2026-07-14",
    works: [
      { title: "アルゴナビス from BanG Dream!", character: "宇治川紫夕" },
      { title: "憂国のモリアーティ", character: "ウィギンズ" },
      { title: "天才王子の赤字国家再生術", character: "ナナキ・ラーレイ" },
      { title: "リコリス・リコイル", character: "ロボ太" },
      { title: "異世界ワンターンキル姉さん", character: "軍場朝陽" },
      { title: "デッドマウント・デスプレイ", character: "四乃山ポルカ" },
      { title: "AYAKA -あやか-", character: "天乃夜胡" },
      { title: "ビックリメン", character: "ピーター" },
      { title: "ヒプノシスマイク-Division Rap Battle-Rhyme Anima +", character: "四十物十四" },
      { title: "ヴァンパイア男子寮", character: "樹里" },
    ],
  },
};
