// 声優個人ページ（app/person/[name]/[year]/[season]/page.tsx）が表示する「代表作＋役名」を
// 人力で補完するデータ。Annict GraphQL APIには「声優→出演作品」の逆引きクエリが存在せず
// （Person型にcastsCount等はあるが作品一覧を返すフィールドが無い）、全出演作品を機械的に
// 集計しようとすると全クール分のAnnictデータを舐める必要がありAnnictへの負荷が大きい
// （docs/operations.mdの「⑪」、および[[annict-load-consideration]]の方針に反する）。
// そのため「今期の出演作品」はこれまでどおりAnnictのリアルタイムデータで自動表示し、
// 「代表作＋役名」だけをWikipedia等の一次情報から人力で確認・追記する運用にした
// （content/works/{id}.json の人力コンテンツと同じ思想）。
//
// キーはAnnictのcasts.nameと完全一致させる（app/person/[name]/... のnameパラメータと同じ文字列）。
export interface PersonFilmographyEntry {
  works: { title: string; character: string }[];
  // 出典（Wikipedia記事等）のURL。CLAUDE.mdの「一次情報のみ・出典明示」方針に従い必須とする。
  sourceUrl: string;
  // 確認日（"YYYY-MM-DD"）。データが古くなっていないかの目安。
  confirmedDate: string;
}

export const PERSON_FILMOGRAPHY: Record<string, PersonFilmographyEntry> = {
  豊口めぐみ: {
    sourceUrl: "https://ja.wikipedia.org/wiki/豊口めぐみ",
    confirmedDate: "2026-07-13",
    works: [
      { title: "アリスSOS", character: "アリス" },
      { title: "デュアル！ぱられルンルン物語", character: "羅螺みつき / ミス・ラー" },
      { title: "超GALS！寿蘭", character: "寿蘭" },
      { title: "ポケットモンスター ダイヤモンド&パール", character: "ヒカリ" },
      { title: "鋼の錬金術師", character: "ウィンリィ・ロックベル" },
      { title: "マリア様がみてる", character: "佐藤聖" },
      { title: "いちご100%", character: "西野つかさ" },
      { title: "BLACK LAGOON", character: "レヴィ" },
      { title: "マクロスF", character: "クラン・クラン" },
      { title: "スイートプリキュア♪", character: "黒川エレン / キュアビート" },
      { title: "IS〈インフィニット・ストラトス〉", character: "織斑千冬" },
      { title: "Fate/Zero", character: "ソラウ・ヌァザレ・ソフィアリ" },
      { title: "ダンガンロンパ", character: "江ノ島盾子" },
      { title: "転生したらスライムだった件", character: "大賢者 / 智慧之王" },
      { title: "ウマ娘 プリティーダービー", character: "東条ハナ" },
    ],
  },
  早見沙織: {
    sourceUrl: "https://ja.wikipedia.org/wiki/早見沙織",
    confirmedDate: "2026-07-14",
    works: [
      { title: "俺の妹がこんなに可愛いわけがない", character: "新垣あやせ" },
      { title: "あの日見た花の名前を僕達はまだ知らない。", character: "鶴見知利子（つるこ）" },
      { title: "やはり俺の青春ラブコメはまちがっている。", character: "雪ノ下雪乃" },
      { title: "アイドルマスター シンデレラガールズ", character: "高垣楓" },
      { title: "魔法科高校の劣等生", character: "司波深雪" },
      { title: "魔法つかいプリキュア！", character: "花海ことは／キュアフェリーチェ" },
      { title: "鬼滅の刃", character: "胡蝶しのぶ" },
      { title: "SPY×FAMILY", character: "ヨル・フォージャー" },
      { title: "そらのおとしもの", character: "イカロス" },
      { title: "セキレイ", character: "結" },
      { title: "ワンパンマン", character: "地獄のフブキ" },
      { title: "賭ケグルイ", character: "蛇喰夢子" },
    ],
  },
  関根明良: {
    sourceUrl: "https://ja.wikipedia.org/wiki/関根明良",
    confirmedDate: "2026-07-14",
    works: [
      { title: "プリンセス・プリンシパル", character: "プリンセス" },
      { title: "アイカツ！", character: "藤原みやび" },
      { title: "魔法少女特殊戦あすか", character: "夢源くるみ" },
      { title: "旗揚！けものみち", character: "シグレ" },
      { title: "神之塔 -Tower of God-", character: "アナク・ザハード" },
      { title: "その着せ替え人形は恋をする", character: "山内瑠音" },
      { title: "明日ちゃんのセーラー服", character: "谷川景" },
      { title: "BIRDIE WING -Golf Girls' Story-", character: "リリィ・リップマン" },
      { title: "ひろがるスカイ！プリキュア", character: "ソラ・ハレワタール／キュアスカイ" },
      { title: "先輩はおとこのこ", character: "蒼井咲" },
      { title: "杖と剣のウィストリア", character: "エルファリア・アルヴィス・セルフォルト" },
    ],
  },
  阿座上洋平: {
    sourceUrl: "https://ja.wikipedia.org/wiki/阿座上洋平",
    confirmedDate: "2026-07-14",
    works: [
      { title: "クロムクロ", character: "青馬剣之介時貞" },
      { title: "ピアシェ〜私のイタリアン〜", character: "近野桐秀" },
      { title: "ようこそ実力至上主義の教室へ", character: "橋本正義" },
      { title: "新サクラ大戦 the Animation", character: "神山誠十郎" },
      { title: "ゴジラ S.P〈シンギュラポイント〉", character: "佐藤隼也" },
      { title: "白い砂のアクアトープ", character: "屋嘉間志空也" },
      { title: "D_CIDE TRAUMEREI THE ANIMATION", character: "織田龍平" },
      { title: "ラブオールプレー", character: "榊翔平" },
      { title: "それでも歩は寄せてくる", character: "田中歩" },
      { title: "虫かぶり姫", character: "アーヴィン・オランザ" },
      { title: "機動戦士ガンダム 水星の魔女", character: "グエル・ジェターク" },
      { title: "鴨乃橋ロンの禁断推理", character: "鴨乃橋ロン" },
      { title: "青のミブロ", character: "土方歳三" },
    ],
  },
  安済知佳: {
    sourceUrl: "https://ja.wikipedia.org/wiki/安済知佳",
    confirmedDate: "2026-07-14",
    works: [
      { title: "あにゃまる探偵 キルミンずぅ", character: "御子神ナギサ" },
      { title: "棺姫のチャイカ", character: "チャイカ・トラバント" },
      { title: "響け！ユーフォニアム", character: "高坂麗奈" },
      { title: "クズの本懐", character: "安楽岡花火" },
      { title: "灰と幻想のグリムガル", character: "メリイ" },
      { title: "同居人はひざ、時々、頭のうえ。", character: "押守なな" },
      { title: "地縛少年花子くん", character: "七峰桜" },
      { title: "リコリス・リコイル", character: "錦木千束" },
      { title: "進撃の巨人", character: "ミーナ・カロライナ" },
      { title: "SSSS.DYNAZENON", character: "飛鳥川ちせ" },
      { title: "ぐらんぶる", character: "古手川千紗" },
    ],
  },
  石川由依: {
    sourceUrl: "https://ja.wikipedia.org/wiki/石川由依",
    confirmedDate: "2026-07-14",
    works: [
      { title: "進撃の巨人", character: "ミカサ・アッカーマン" },
      { title: "ヴァイオレット・エヴァーガーデン", character: "ヴァイオレット・エヴァーガーデン" },
      { title: "トロピカル〜ジュ！プリキュア", character: "一之瀬みのり／キュアパパイア" },
      { title: "アイカツ！", character: "新条ひなき" },
      { title: "ガンダムビルドファイターズ", character: "コウサカ・チナ" },
      { title: "エロマンガ先生", character: "高砂智恵" },
      { title: "蒼穹のファフナー EXODUS", character: "水鏡美三香" },
      { title: "クオリディア・コード", character: "宇多良カナリア" },
      { title: "ガーリッシュ ナンバー", character: "片倉京" },
      { title: "けものフレンズ2", character: "キュルル" },
      { title: "聖女の魔力は万能です", character: "セイ／小鳥遊聖" },
      { title: "NieR:Automata Ver1.1a", character: "2B" },
    ],
  },
  水瀬いのり: {
    sourceUrl: "https://ja.wikipedia.org/wiki/水瀬いのり",
    confirmedDate: "2026-07-14",
    works: [
      { title: "ご注文はうさぎですか？", character: "香風智乃（チノ）" },
      { title: "心が叫びたがってるんだ。", character: "成瀬順" },
      { title: "ダンジョンに出会いを求めるのは間違っているだろうか", character: "ヘスティア" },
      { title: "Re:ゼロから始める異世界生活", character: "レム" },
      { title: "五等分の花嫁", character: "中野五月" },
      { title: "がっこうぐらし！", character: "丈槍由紀" },
      { title: "戦姫絶唱シンフォギア", character: "キャロル・マールス・ディーンハイム" },
      { title: "恋愛ラボ", character: "棚橋鈴音" },
      { title: "ViVid Strike!", character: "フーカ・レヴェントン" },
      { title: "少女終末旅行", character: "チト" },
      { title: "宇宙よりも遠い場所", character: "玉木マリ" },
      { title: "政宗くんのリベンジ", character: "小岩井吉乃" },
      { title: "キラキラ☆プリキュアアラモード", character: "キラ星シエル／キュアパルフェ" },
      { title: "青春ブタ野郎シリーズ", character: "牧之原翔子" },
    ],
  },
  東山奈央: {
    sourceUrl: "https://ja.wikipedia.org/wiki/東山奈央",
    confirmedDate: "2026-07-14",
    works: [
      { title: "神のみぞ知るセカイ", character: "中川かのん" },
      { title: "異国迷路のクロワーゼ The Animation", character: "湯音" },
      { title: "戦姫絶唱シンフォギア", character: "寺島詩織" },
      { title: "咲-Saki- 阿知賀編", character: "新子憧" },
      { title: "ラブライブ！", character: "高坂雪穂" },
      { title: "やはり俺の青春ラブコメはまちがっている。", character: "由比ヶ浜結衣" },
      { title: "きんいろモザイク", character: "九条カレン" },
      { title: "蒼き鋼のアルペジオ", character: "八月一日静" },
      { title: "ニセコイ", character: "桐崎千棘" },
      { title: "マクロスΔ", character: "レイナ・プラウラー" },
      { title: "ゆるキャン△", character: "志摩リン" },
      { title: "響け！ユーフォニアム", character: "傘木希美" },
      { title: "彼女、お借りします", character: "更科瑠夏" },
    ],
  },
  "M・A・O": {
    sourceUrl: "https://ja.wikipedia.org/wiki/M・A・O",
    confirmedDate: "2026-07-14",
    works: [
      { title: "クッキンアイドル アイ！マイ！まいん！", character: "キラキラ" },
      { title: "帰宅部活動記録", character: "あざらし" },
      { title: "サムライフラメンコ", character: "三澤瑞希" },
      { title: "DD北斗の拳", character: "リン" },
      { title: "愛・天地無用！", character: "沙流葉七" },
      { title: "俺、ツインテールになります。", character: "桜川尊" },
      { title: "極黒のブリュンヒルデ", character: "カズミ＝シュリーレンツァウアー" },
      { title: "がっこうぐらし！", character: "若狭悠里" },
      { title: "機動戦士ガンダム 鉄血のオルフェンズ", character: "ジュリエッタ・ジュリス" },
      { title: "クラシカロイド", character: "バダジェフスカ" },
      { title: "競女!!!!!!!!", character: "宮田さやか" },
      { title: "クロムクロ", character: "白羽由希奈" },
      { title: "転生したらスライムだった件", character: "シオン" },
      { title: "ようこそ実力至上主義の教室へ", character: "佐倉愛里" },
      { title: "からかい上手の高木さん", character: "天川ユカリ" },
      { title: "炎炎ノ消防隊", character: "アイリス" },
    ],
  },
  戸松遥: {
    sourceUrl: "https://ja.wikipedia.org/wiki/戸松遥",
    confirmedDate: "2026-07-14",
    works: [
      { title: "あの日見た花の名前を僕達はまだ知らない。", character: "安城鳴子（あなる）" },
      { title: "ソードアート・オンライン", character: "アスナ／結城明日奈" },
      { title: "ハピネスチャージプリキュア！", character: "氷川いおな／キュアフォーチュン" },
      { title: "妖怪ウォッチ", character: "ケータ／天野景太" },
      { title: "かんなぎ", character: "ナギ" },
      { title: "絶対可憐チルドレン", character: "三宮紫穂" },
      { title: "To LOVEる -とらぶる-", character: "ララ・サタリン・デビルーク" },
      { title: "神曲奏界ポリフォニカ", character: "コーティカルテ・アパ・ラグランジェス" },
      { title: "ダーリン・イン・ザ・フランキス", character: "ゼロツー" },
      { title: "ヴァイオレット・エヴァーガーデン", character: "アイリス・カナリー" },
    ],
  },
  大塚芳忠: {
    sourceUrl: "https://ja.wikipedia.org/wiki/大塚芳忠",
    confirmedDate: "2026-07-14",
    works: [
      { title: "機動戦士Ζガンダム", character: "ヤザン・ゲーブル" },
      { title: "機甲戦記ドラグナー", character: "タップ・オセアノ" },
      { title: "機動武闘伝Gガンダム", character: "チボデー・クロケット" },
      { title: "∀ガンダム", character: "ギャバン・グーニー" },
      { title: "最遊記シリーズ", character: "你健一／烏哭三蔵" },
      { title: "NARUTO -ナルト-", character: "自来也" },
      { title: "銀魂", character: "阿伏兎" },
      { title: "幼女戦記", character: "ゼートゥーア" },
      { title: "ゴールデンカムイ", character: "鶴見中尉" },
      { title: "転生したらスライムだった件", character: "ハクロウ" },
      { title: "亜人", character: "佐藤" },
      { title: "文豪ストレイドッグス", character: "夏目漱石" },
      { title: "バキ", character: "ビスケット・オリバ" },
    ],
  },
  高橋李依: {
    sourceUrl: "https://ja.wikipedia.org/wiki/高橋李依",
    confirmedDate: "2026-07-14",
    works: [
      { title: "この素晴らしい世界に祝福を！", character: "めぐみん" },
      { title: "Re:ゼロから始める異世界生活", character: "エミリア" },
      { title: "魔法つかいプリキュア！", character: "朝日奈みらい／キュアミラクル" },
      { title: "【推しの子】", character: "アイ" },
      { title: "それが声優！", character: "一ノ瀬双葉" },
      { title: "からかい上手の高木さん", character: "高木さん" },
      { title: "ゆるキャン△", character: "斉藤恵那" },
      { title: "Fate/Grand Order", character: "マシュ・キリエライト（2代目）" },
      { title: "がっこうぐらし！", character: "直樹美紀" },
      { title: "彼女、お借りします", character: "桜沢墨" },
      { title: "地獄楽", character: "杠" },
    ],
  },
  日高里菜: {
    sourceUrl: "https://ja.wikipedia.org/wiki/日高里菜",
    confirmedDate: "2026-07-14",
    works: [
      { title: "とある魔術の禁書目録", character: "打ち止め〈ラストオーダー〉" },
      { title: "ソードアート・オンライン", character: "シリカ／綾野珪子" },
      { title: "ロウきゅーぶ！", character: "香椎愛莉" },
      { title: "アクセル・ワールド", character: "ニコ〈上月由仁子／スカーレット・レイン〉" },
      { title: "転生したらスライムだった件", character: "ミリム" },
      { title: "盾の勇者の成り上がり", character: "フィーロ" },
      { title: "ようこそ実力至上主義の教室へ", character: "坂柳有栖" },
      { title: "戦姫絶唱シンフォギアAXZ", character: "プレラーティ" },
      { title: "艦隊これくしょん -艦これ-", character: "睦月" },
      { title: "トロピカル〜ジュ！プリキュア", character: "ローラ／キュアラメール" },
    ],
  },
  内山昂輝: {
    sourceUrl: "https://ja.wikipedia.org/wiki/内山昂輝",
    confirmedDate: "2026-07-14",
    works: [
      { title: "キングダム ハーツ シリーズ", character: "ロクサス／ヴェントゥス" },
      { title: "機動戦士ガンダムUC", character: "バナージ・リンクス" },
      { title: "ピンポン THE ANIMATION", character: "スマイル／月本誠" },
      { title: "DEVILMAN crybaby", character: "不動明" },
      { title: "僕のヒーローアカデミア", character: "死柄木弔" },
      { title: "ハイキュー!!", character: "月島蛍" },
      { title: "呪術廻戦", character: "狗巻棘" },
      { title: "ソウルイーター", character: "ソウル＝イーター" },
      { title: "屍鬼", character: "結城夏野" },
      { title: "ニセコイ", character: "一条楽" },
      { title: "Charlotte", character: "乙坂有宇" },
      { title: "ユーリ!!! on ICE", character: "ユーリ・プリセツキー" },
      { title: "ホリミヤ", character: "宮村伊澄" },
    ],
  },
  安元洋貴: {
    sourceUrl: "https://ja.wikipedia.org/wiki/安元洋貴",
    confirmedDate: "2026-07-14",
    works: [
      { title: "BLEACH", character: "茶渡泰虎" },
      { title: "鬼灯の冷徹", character: "鬼灯" },
      { title: "弱虫ペダル", character: "金城真護" },
      { title: "ヘタリア Axis Powers", character: "ドイツ" },
      { title: "ソードアート・オンライン", character: "エギル" },
      { title: "FAIRY TAIL", character: "エルフマン・ストラウス" },
      { title: "ワンパンマン", character: "キング" },
      { title: "黒執事", character: "アグニ" },
      { title: "この素晴らしい世界に祝福を！", character: "デュラハン" },
      { title: "ドルアーガの塔", character: "ウトゥ" },
      { title: "食戟のソーマ", character: "美作昴" },
      { title: "ユーリ!!! on ICE", character: "クリストフ・ジャコメッティ" },
    ],
  },
  小清水亜美: {
    sourceUrl: "https://ja.wikipedia.org/wiki/小清水亜美",
    confirmedDate: "2026-07-14",
    works: [
      { title: "明日のナージャ", character: "ナージャ・アップルフィールド" },
      { title: "スクールランブル", character: "塚本天満" },
      { title: "おねがいマイメロディ", character: "桜塚美紀" },
      { title: "交響詩篇エウレカセブン", character: "アネモネ" },
      { title: "狼と香辛料", character: "ホロ" },
      { title: "コードギアス 反逆のルルーシュ", character: "紅月カレン" },
      { title: "スイートプリキュア♪", character: "北条響／キュアメロディ" },
      { title: "ストライクウィッチーズ", character: "シャーロット・E・イェーガー" },
      { title: "Persona4 the ANIMATION", character: "天城雪子" },
      { title: "キルラキル", character: "纏流子" },
    ],
  },
  本渡楓: {
    sourceUrl: "https://ja.wikipedia.org/wiki/本渡楓",
    confirmedDate: "2026-07-14",
    works: [
      { title: "かみさまみならい ヒミツのここたま", character: "四葉こころ" },
      { title: "不思議なソメラちゃん", character: "野乃本ククル" },
      { title: "レガリア The Three Sacred Stars", character: "ユインシエル・アステリア" },
      { title: "競女!!!!!!!!", character: "青葉風音" },
      { title: "ガーリッシュナンバー", character: "久我山八重" },
      { title: "うらら迷路帖", character: "巽紺" },
      { title: "亜人ちゃんは語りたい", character: "小鳥遊ひかり" },
      { title: "バトルガール ハイスクール", character: "煌上花音" },
      { title: "アニメガタリズ", character: "阿佐ヶ谷未乃愛" },
      { title: "こみっくがーるず", character: "恋塚小夢" },
      { title: "ヒナまつり", character: "三嶋瞳" },
      { title: "ちおちゃんの通学路", character: "細川雪" },
      { title: "ゾンビランドサガ", character: "源さくら" },
      { title: "色づく世界の明日から", character: "月白琥珀" },
      { title: "刀使ノ巫女", character: "衛藤可奈美" },
      { title: "魔女の旅々", character: "イレイナ" },
    ],
  },
  長縄まりあ: {
    sourceUrl: "https://ja.wikipedia.org/wiki/長縄まりあ",
    confirmedDate: "2026-07-14",
    works: [
      { title: "小林さんちのメイドラゴン", character: "カンナ／カンナカムイ" },
      { title: "はたらく細胞", character: "血小板" },
      { title: "スロウスタート", character: "千石冠" },
      { title: "ステラのまほう", character: "本田珠輝" },
      { title: "女子高生の無駄づかい", character: "ロリ／百井咲久" },
      { title: "アズールレーン", character: "ラフィー" },
      { title: "BNA ビー・エヌ・エー", character: "日渡なずな" },
      { title: "わんだふるぷりきゅあ！", character: "犬飼こむぎ／キュアワンダフル" },
      { title: "君のことが大大大大大好きな100人の彼女", character: "好本静" },
      { title: "ワールドダイスター", character: "新妻八恵" },
      { title: "六畳間の侵略者!?", character: "ティアミリス・グレ・フォルトーゼ" },
      { title: "奇異太郎少年の妖怪絵日記", character: "雪娘" },
      { title: "異世界薬局", character: "ブランシュ・ド・メディシス" },
    ],
  },
  村瀬歩: {
    sourceUrl: "https://ja.wikipedia.org/wiki/村瀬歩",
    confirmedDate: "2026-07-14",
    works: [
      { title: "ハイキュー!!", character: "日向翔陽" },
      { title: "新世界より", character: "青沼瞬（14歳）" },
      { title: "ブラッククローバー", character: "ラック・ボルティア" },
      { title: "魔入りました！入間くん", character: "鈴木入間" },
      { title: "Dr.STONE", character: "銀狼" },
      { title: "王様ランキング", character: "カゲ" },
      { title: "かくしごと", character: "芥子駆" },
      { title: "あんさんぶるスターズ!", character: "姫宮桃李" },
      { title: "ひろがるスカイ！プリキュア", character: "夕凪ツバサ／キュアウィング" },
      { title: "さらざんまい", character: "矢逆一稀" },
      { title: "ダイヤのA", character: "由井薫" },
    ],
  },
  子安武人: {
    sourceUrl: "https://ja.wikipedia.org/wiki/子安武人",
    confirmedDate: "2026-07-14",
    works: [
      { title: "天空戦記シュラト", character: "夜叉王ガイ" },
      { title: "楽しいムーミン一家", character: "スナフキン" },
      { title: "宇宙の騎士テッカマンブレード", character: "テッカマン・エビル／相羽シンヤ" },
      { title: "ビーストウォーズ 超生命体トランスフォーマー", character: "コンボイ" },
      { title: "新機動戦記ガンダムW", character: "ゼクス・マーキス" },
      { title: "ふしぎ遊戯", character: "星宿" },
      { title: "スレイヤーズ", character: "赤法師レゾ" },
      { title: "新世紀エヴァンゲリオン", character: "青葉シゲル" },
      { title: "少女革命ウテナ", character: "桐生冬芽" },
      { title: "頭文字D", character: "高橋涼介" },
      { title: "∀ガンダム", character: "ギム・ギンガナム" },
      { title: "機動戦士ガンダムSEED", character: "ムウ・ラ・フラガ" },
      { title: "銀魂", character: "高杉晋助" },
      { title: "進撃の巨人", character: "ジーク（獣の巨人）" },
      { title: "Re:ゼロから始める異世界生活", character: "ロズワール" },
    ],
  },
  ファイルーズあい: {
    sourceUrl: "https://ja.wikipedia.org/wiki/ファイルーズあい",
    confirmedDate: "2026-07-14",
    works: [
      { title: "ダンベル何キロ持てる?", character: "紗倉ひびき" },
      { title: "推しが武道館いってくれたら死ぬ", character: "えりぴよ" },
      { title: "神田川JET GIRLS", character: "エミリー・オレンジ" },
      { title: "トロピカル〜ジュ！プリキュア", character: "夏海まなつ／キュアサマー" },
      { title: "ジョジョの奇妙な冒険 ストーンオーシャン", character: "空条徐倫" },
      { title: "チェンソーマン", character: "パワー" },
      { title: "陰の実力者になりたくて！", character: "デルタ" },
      { title: "悪役令嬢レベル99", character: "ユミエラ・ドルクネス" },
      { title: "怪獣8号", character: "四ノ宮キコル" },
    ],
  },
  白石晴香: {
    sourceUrl: "https://ja.wikipedia.org/wiki/白石晴香",
    confirmedDate: "2026-07-14",
    works: [
      { title: "コクリコ坂から", character: "松崎空" },
      { title: "ガラスの仮面ですがZ", character: "姫川亜弓" },
      { title: "干物妹！うまるちゃん", character: "本場切絵" },
      { title: "あんハピ♪", character: "雲雀丘瑠璃" },
      { title: "山賊の娘ローニャ", character: "ローニャ" },
      { title: "ゴールデンカムイ", character: "アシㇼパ" },
      { title: "うちのメイドがウザすぎる！", character: "高梨ミーシャ" },
      { title: "アニマエール！", character: "牛久花和" },
      { title: "ぼくたちは勉強ができない", character: "古橋文乃" },
      { title: "俺を好きなのはお前だけかよ", character: "ひまわり（日向葵）" },
      { title: "アクションヒロイン チアフルーツ", character: "紫村果音" },
      { title: "セントールの悩み", character: "名楽羌子" },
      { title: "転生したらスライムだった件", character: "アリス" },
      { title: "ラブライブ!スーパースター!!", character: "ココノ" },
      { title: "明日ちゃんのセーラー服", character: "戸鹿野舞衣" },
    ],
  },
  日笠陽子: {
    sourceUrl: "https://ja.wikipedia.org/wiki/日笠陽子",
    confirmedDate: "2026-07-14",
    works: [
      { title: "けいおん!", character: "秋山澪" },
      { title: "キングダム", character: "羌瘣" },
      { title: "はたらく魔王さま!", character: "遊佐恵美" },
      { title: "戦姫絶唱シンフォギア", character: "マリア・カデンツァヴナ・イヴ" },
      { title: "SHAMAN KING", character: "麻倉葉" },
      { title: "ハイスクールD×D", character: "リアス・グレモリー" },
      { title: "IS〈インフィニット・ストラトス〉", character: "篠ノ之箒" },
      { title: "これはゾンビですか?", character: "セラ" },
      { title: "生徒会役員共", character: "天草シノ" },
      { title: "ダンガンロンパ", character: "霧切響子" },
      { title: "ヤマノススメ", character: "斎藤楓" },
      { title: "BanG Dream!", character: "宇田川巴" },
      { title: "ありふれた職業で世界最強", character: "ティオ・クラルス" },
      { title: "Dr.STONE", character: "北東西南" },
    ],
  },
  田村ゆかり: {
    sourceUrl: "https://ja.wikipedia.org/wiki/田村ゆかり",
    confirmedDate: "2026-07-14",
    works: [
      { title: "ひぐらしのなく頃に", character: "古手梨花" },
      { title: "極上生徒会", character: "蘭堂りの／プッチャン" },
      { title: "魔法少女リリカルなのは", character: "高町なのは" },
      { title: "ギャラクシーエンジェル", character: "蘭花・フランボワーズ" },
      { title: "D.C. 〜ダ・カーポ〜", character: "芳乃さくら" },
      { title: "スクライド", character: "由詑かなみ" },
      { title: "Kanon", character: "川澄舞" },
      { title: "NARUTO -ナルト-", character: "テンテン" },
      { title: "黒執事", character: "エリザベス・エセル・コーディリア・ミッドフォード" },
      { title: "灼眼のシャナ", character: "ティリエル" },
      { title: "かしまし〜ガール・ミーツ・ガール〜", character: "来栖とまり" },
      { title: "HUGっと！プリキュア", character: "ルールー・アムール／キュアアムール" },
    ],
  },
  榎木淳弥: {
    sourceUrl: "https://ja.wikipedia.org/wiki/榎木淳弥",
    confirmedDate: "2026-07-14",
    works: [
      { title: "呪術廻戦", character: "虎杖悠仁" },
      { title: "ジョジョの奇妙な冒険 黄金の風", character: "パンナコッタ・フーゴ" },
      { title: "BEASTARS", character: "ジャック" },
      { title: "ベイブレードバースト", character: "紅シュウ" },
      { title: "風が強く吹いている", character: "城太郎（ジョータ）" },
      { title: "アイドルマスター SideM", character: "舞田類" },
      { title: "ID:INVADED イド:インヴェイデッド", character: "若鹿一雄" },
      { title: "トニカクカワイイ", character: "由崎星空" },
      { title: "はたらく細胞BLACK", character: "赤血球" },
      { title: "八男って、それはないでしょう!", character: "ヴェンデリン" },
      { title: "活撃 刀剣乱舞", character: "堀川国広" },
      { title: "ブギーポップは笑わない", character: "早乙女正美" },
      { title: "刀剣乱舞-花丸-", character: "堀川国広" },
      { title: "カードファイト!! ヴァンガード", character: "綺場シオン" },
      { title: "東京リベンジャーズ", character: "乾青宗" },
    ],
  },
  梅原裕一郎: {
    sourceUrl: "https://ja.wikipedia.org/wiki/梅原裕一郎",
    confirmedDate: "2026-07-14",
    works: [
      { title: "美男高校地球防衛部LOVE!", character: "由布院煙" },
      { title: "終わりのセラフ", character: "レーネ・シム" },
      { title: "アクエリオンロゴス", character: "空篠翼人" },
      { title: "ガッチャマン クラウズ インサイト", character: "鈴木理詰夢" },
      { title: "赤髪の白雪姫", character: "ミツヒデ" },
      { title: "ミリオンドール", character: "リュウサン" },
      { title: "ヤングブラック・ジャック", character: "間黒男" },
      { title: "機動戦士ガンダム 鉄血のオルフェンズ", character: "ユージン・セブンスターク" },
      { title: "タイガーマスクW", character: "藤井タクマ／タイガー・ザ・ダーク" },
      { title: "ようこそ実力至上主義の教室へ", character: "堀北学" },
      { title: "キャプテン翼", character: "若島津健" },
      { title: "ゴブリンスレイヤー", character: "ゴブリンスレイヤー" },
      { title: "あんさんぶるスターズ!", character: "蓮巳敬人" },
      { title: "鬼滅の刃 刀鍛冶の里編", character: "積怒" },
    ],
  },
  坂泰斗: {
    sourceUrl: "https://ja.wikipedia.org/wiki/坂泰斗",
    confirmedDate: "2026-07-14",
    works: [
      { title: "魔術士オーフェンはぐれ旅", character: "ハーティア" },
      { title: "美少年探偵団", character: "咲口長広" },
      { title: "お隣の天使様にいつの間にか駄目人間にされていた件", character: "藤宮周" },
      { title: "俺だけレベルアップな件", character: "水篠旬" },
      { title: "VAZZROCK THE ANIMATION", character: "立花歩" },
      { title: "転生貴族、鑑定スキルで成り上がる", character: "リーツ・ミューセス" },
      { title: "妖怪学校の先生はじめました!", character: "泥田耕太郎" },
      { title: "SYNDUALITY Noir", character: "マハト〈黒仮面〉" },
    ],
  },
  榊原優希: {
    sourceUrl: "https://ja.wikipedia.org/wiki/榊原優希",
    confirmedDate: "2026-07-14",
    works: [
      { title: "アルゴナビス from BanG Dream!", character: "宇治川紫夕" },
      { title: "憂国のモリアーティ", character: "ウィギンズ" },
      { title: "天才王子の赤字国家再生術", character: "ナナキ・ラーレイ" },
      { title: "リコリス・リコイル", character: "ロボ太" },
      { title: "異世界ワンターンキル姉さん", character: "軍場朝陽" },
      { title: "デッドマウント・デスプレイ", character: "四乃山ポルカ" },
      { title: "AYAKA -あやか-", character: "天乃夜胡" },
      { title: "ビックリメン", character: "ピーター" },
      { title: "ヒプノシスマイク-Division Rap Battle-Rhyme Anima +", character: "四十物十四" },
      { title: "ヴァンパイア男子寮", character: "樹里" },
    ],
  },
  稲田徹: {
    sourceUrl: "https://ja.wikipedia.org/wiki/稲田徹",
    confirmedDate: "2026-07-14",
    works: [
      { title: "∀ガンダム", character: "ハリー・オード" },
      { title: "スーパーロボット大戦OG -ディバイン・ウォーズ-", character: "エルザム・V・ブランシュタイン" },
      { title: "SAMURAI 7", character: "ゴロベエ" },
      { title: "ツバサ・クロニクル", character: "黒鋼" },
      { title: "喰霊 -零-", character: "岩端晃司" },
      { title: "魁!!クロマティ高校", character: "前田彰" },
      { title: "キルラキル", character: "蟇郡苛" },
      { title: "旗揚！けものみち", character: "MAO／マカデミアンオーガ" },
      { title: "僕のヒーローアカデミア", character: "エンデヴァー" },
    ],
  },
  内山夕実: {
    sourceUrl: "https://ja.wikipedia.org/wiki/内山夕実",
    confirmedDate: "2026-07-14",
    works: [
      { title: "Aチャンネル", character: "ナギ（天王寺渚）" },
      { title: "侵略!?イカ娘", character: "望月知美" },
      { title: "咲-Saki-", character: "鷺森灼" },
      { title: "好きっていいなよ。", character: "武藤愛子" },
      { title: "貧乏神が!", character: "紅葉" },
      { title: "きんいろモザイク", character: "猪熊陽子" },
      { title: "蒼き鋼のアルペジオ", character: "キリシマ" },
      { title: "ストライク・ザ・ブラッド", character: "仙都木優麻" },
      { title: "魔法科高校の劣等生", character: "千葉エリカ" },
      { title: "結城友奈は勇者である", character: "犬吠埼風" },
      { title: "オーバーロード", character: "マーレ・ベロ・フィオーレ" },
      { title: "Re:ゼロから始める異世界生活", character: "パック" },
      { title: "無職転生", character: "ルーデウス・グレイラット" },
      { title: "東京リベンジャーズ", character: "佐野エマ" },
      { title: "夜桜さんちの大作戦", character: "夜桜七悪" },
    ],
  },
  悠木碧: {
    sourceUrl: "https://ja.wikipedia.org/wiki/悠木碧",
    confirmedDate: "2026-07-14",
    works: [
      { title: "魔法少女まどか☆マギカ", character: "鹿目まどか" },
      { title: "君の名は。", character: "名取早耶香" },
      { title: "妖怪ウォッチ", character: "未空イナホ" },
      { title: "戦姫絶唱シンフォギア", character: "立花響" },
      { title: "ポケットモンスター ベストウイッシュ", character: "アイリス" },
      { title: "やはり俺の青春ラブコメはまちがっている。", character: "比企谷小町" },
      { title: "幼女戦記", character: "ターニャ・デグレチャフ" },
      { title: "ヒーリングっど♥プリキュア", character: "花寺のどか／キュアグレース" },
      { title: "薬屋のひとりごと", character: "猫猫" },
      { title: "僕のヒーローアカデミア", character: "蛙吹梅雨" },
      { title: "七つの大罪", character: "ディアンヌ" },
      { title: "ソードアート・オンライン", character: "ユウキ／紺野木綿季" },
    ],
  },
  三木眞一郎: {
    sourceUrl: "https://ja.wikipedia.org/wiki/三木眞一郎",
    confirmedDate: "2026-07-14",
    works: [
      { title: "ポケットモンスター", character: "コジロウ" },
      { title: "機動戦士ガンダム00", character: "ロックオン・ストラトス（ニール・ディランディ／ライル・ディランディ）" },
      { title: "BLEACH", character: "浦原喜助" },
      { title: "頭文字D", character: "藤原拓海" },
      { title: "銀魂", character: "坂本辰馬" },
      { title: "天空のエスカフローネ", character: "アレン・シェザール" },
      { title: "鋼の錬金術師 FULLMETAL ALCHEMIST", character: "ロイ・マスタング" },
      { title: "薄桜鬼", character: "土方歳三" },
      { title: "幼女戦記", character: "レルゲン" },
    ],
  },
  瀬戸麻沙美: {
    sourceUrl: "https://ja.wikipedia.org/wiki/瀬戸麻沙美",
    confirmedDate: "2026-07-14",
    works: [
      { title: "ちはやふる", character: "綾瀬千早" },
      { title: "放浪息子", character: "高槻よしの" },
      { title: "TARI TARI", character: "宮本来夏" },
      { title: "戦姫絶唱シンフォギア", character: "友里あおい" },
      { title: "ストライク・ザ・ブラッド", character: "藍羽浅葱" },
      { title: "革命機ヴァルヴレイヴ", character: "指南ショーコ" },
      { title: "ウィッチクラフトワークス", character: "火々里綾火" },
      { title: "輪廻のラグランジェ", character: "ラン" },
      { title: "マクロスΔ", character: "ミラージュ・ファリーナ・ジーナス" },
      { title: "青春ブタ野郎シリーズ", character: "桜島麻衣" },
      { title: "盾の勇者の成り上がり", character: "ラフタリア" },
      { title: "呪術廻戦", character: "釘崎野薔薇" },
      { title: "文豪ストレイドッグス", character: "樋口一葉" },
      { title: "トロピカル〜ジュ！プリキュア", character: "滝沢あすか／キュアフラミンゴ" },
    ],
  },
  矢野妃菜喜: {
    sourceUrl: "https://ja.wikipedia.org/wiki/矢野妃菜喜",
    confirmedDate: "2026-07-14",
    works: [
      { title: "ラブライブ！虹ヶ咲学園スクールアイドル同好会", character: "高咲侑" },
      { title: "ワンダーエッグ・プライオリティ", character: "沢木桃恵" },
      { title: "SELECTION PROJECT", character: "美山鈴音" },
      { title: "ウマ娘 プリティーダービー", character: "キタサンブラック" },
      { title: "キャノン・バスターズ", character: "S.A.M" },
      { title: "絆のアリル", character: "ハル" },
    ],
  },
  鈴代紗弓: {
    sourceUrl: "https://ja.wikipedia.org/wiki/鈴代紗弓",
    confirmedDate: "2026-07-14",
    works: [
      { title: "ハイスコアガール", character: "大野晶" },
      { title: "荒野のコトブキ飛行隊", character: "キリエ" },
      { title: "かぐや様は告らせたい", character: "白銀圭" },
      { title: "ぼくたちは勉強ができない", character: "武元うるか" },
      { title: "通常攻撃が全体攻撃で二回攻撃のお母さんは好きですか?", character: "ワイズ" },
      { title: "86-エイティシックス-", character: "クレナ・ククミラ" },
      { title: "精霊幻想記", character: "クリスティーナ＝ベルトラム" },
      { title: "失格紋の最強賢者", character: "ルリイ＝アーベントロート" },
      { title: "魔法使い黎明期", character: "ホルト" },
      { title: "くノ一ツバキの胸の内", character: "アサガオ" },
      { title: "シャインポスト", character: "青天国春" },
      { title: "ぼっち・ざ・ろっく！", character: "伊地知虹夏" },
      { title: "女神のカフェテラス", character: "鶴河秋水" },
      { title: "ひきこまり吸血姫の悶々", character: "ヴィルヘイズ" },
    ],
  },
  井澤詩織: {
    sourceUrl: "https://ja.wikipedia.org/wiki/井澤詩織",
    confirmedDate: "2026-07-14",
    works: [
      { title: "メイドインアビス", character: "ナナチ" },
      { title: "ウィッチクラフトワークス", character: "倉石たんぽぽ" },
      { title: "銀の匙 Silver Spoon", character: "吉野まゆみ" },
      { title: "学戦都市アスタリスク", character: "沙々宮紗夜" },
      { title: "ヘボット!", character: "ヘボット" },
      { title: "Lostorage incited WIXOSS", character: "ナナシ" },
      { title: "チェンソーマン", character: "ポチタ" },
      { title: "灼熱の卓球娘", character: "二重丸くるり" },
      { title: "ガールズ&パンツァー", character: "園みどり子／後藤モヨ子／金春希美" },
      { title: "クズの本懐", character: "鴎端のり子（最可）" },
    ],
  },
  小林裕介: {
    sourceUrl: "https://ja.wikipedia.org/wiki/小林裕介",
    confirmedDate: "2026-07-14",
    works: [
      { title: "Re:ゼロから始める異世界生活", character: "ナツキ・スバル" },
      { title: "Dr.STONE", character: "石神千空" },
      { title: "炎炎ノ消防隊", character: "アーサー・ボイル" },
      { title: "幼女戦記", character: "グランツ" },
      { title: "ウィッチクラフトワークス", character: "多華宮仄" },
      { title: "現実主義勇者の王国再建記", character: "ソーマ・カズヤ" },
      { title: "聖女の魔力は万能です", character: "ユーリ・ドレヴェス" },
      { title: "アルスラーン戦記", character: "アルスラーン" },
      { title: "暁のヨナ", character: "スウォン" },
      { title: "異種族レビュアーズ", character: "ゼル" },
    ],
  },
  江口拓也: {
    sourceUrl: "https://ja.wikipedia.org/wiki/江口拓也",
    confirmedDate: "2026-07-14",
    works: [
      { title: "GOSICK -ゴシック-", character: "久城一弥" },
      { title: "黒子のバスケ", character: "小金井慎二" },
      { title: "やはり俺の青春ラブコメはまちがっている。", character: "比企谷八幡" },
      { title: "Re:ゼロから始める異世界生活", character: "ユリウス" },
      { title: "SPY×FAMILY", character: "ロイド・フォージャー" },
      { title: "アイドリッシュセブン", character: "六弥ナギ" },
      { title: "転生したらスライムだった件", character: "ソウエイ" },
      { title: "ブルーロック", character: "雪宮剣優" },
      { title: "東京リベンジャーズ", character: "半間修二" },
      { title: "バキ", character: "花山薫" },
    ],
  },
  星希成奏: {
    sourceUrl: "https://ja.wikipedia.org/wiki/星希成奏",
    confirmedDate: "2026-07-14",
    works: [
      { title: "DARK MOON -黒の月: 月の祭壇-", character: "ジャカ幼少期" },
      { title: "NEEDY GIRL OVERDOSE", character: "禰智禍さま" },
      { title: "スーパーの裏でヤニ吸うふたり", character: "山田／田山" },
      { title: "花織さんは転生しても喧嘩がしたい", character: "皐月まこ" },
      { title: "アイドルマスター シンデレラガールズ劇場 Extra Stage", character: "夢見りあむ" },
      { title: "無期迷途「死恋ラジオ」", character: "デイジー（初代）" },
    ],
  },
  安田陸矢: {
    sourceUrl: "https://ja.wikipedia.org/wiki/安田陸矢",
    confirmedDate: "2026-07-14",
    works: [
      { title: "ベイブレードバースト", character: "墨江フブキ" },
      { title: "美男高校地球防衛部HAPPY KISS!", character: "万座太子" },
      { title: "ベルゼブブ嬢のお気に召すまま。", character: "ミュリン" },
      { title: "厨病激発ボーイ", character: "厨二葉" },
      { title: "魔術士オーフェンはぐれ旅", character: "コミクロン" },
      { title: "ギルドの受付嬢ですが、残業は嫌なのでボスをソロ討伐しようと思います", character: "ロウ・ロズブレンダ" },
      { title: "さわらないで小手指くん", character: "小手指向陽" },
    ],
  },
  坂田将吾: {
    sourceUrl: "https://ja.wikipedia.org/wiki/坂田将吾",
    confirmedDate: "2026-07-14",
    works: [
      { title: "継つぐもも", character: "安次峰あきと" },
      { title: "Fairy蘭丸〜あなたの心お助けします〜", character: "阿以蘭丸" },
      { title: "チェンソーマン", character: "早川アキ" },
      { title: "転生王女と天才令嬢の魔法革命", character: "アルガルド・ボナ・パレッティア" },
      { title: "ブルーアーカイブ The Animation", character: "先生" },
      { title: "恋は双子で割り切れない", character: "白崎純" },
      { title: "MFゴースト", character: "柳田拓也" },
      { title: "治癒魔法の間違った使い方", character: "ウサト" },
      { title: "結婚指輪物語", character: "マルス" },
      { title: "WIND BREAKER", character: "杏西雅紀" },
    ],
  },
  島袋美由利: {
    sourceUrl: "https://ja.wikipedia.org/wiki/島袋美由利",
    confirmedDate: "2026-07-14",
    works: [
      { title: "はねバド!", character: "荒垣なぎさ" },
      { title: "はるかなレシーブ", character: "遠井成美" },
      { title: "音楽少女", character: "具志堅シュープ" },
      { title: "ゆらぎ荘の幽奈さん", character: "湯ノ花幽奈" },
      { title: "ツルネ -風舞高校弓道部-", character: "花沢ゆうな" },
      { title: "キャロル&チューズデイ", character: "キャロル" },
      { title: "グランベルム", character: "小日向満月" },
      { title: "出会って5秒でバトル", character: "多々良りんご" },
      { title: "さよなら私のクラマー", character: "恩田希" },
      { title: "炎炎ノ消防隊", character: "因果春日谷" },
      { title: "ちいかわ", character: "シーサー" },
      { title: "ひきこまり吸血姫の悶々", character: "アマツ・カルラ" },
    ],
  },
  武内駿輔: {
    sourceUrl: "https://ja.wikipedia.org/wiki/武内駿輔",
    confirmedDate: "2026-07-14",
    works: [
      { title: "アイドルマスター シンデレラガールズ", character: "プロデューサー" },
      { title: "ダイヤのA", character: "結城将司" },
      { title: "ALL OUT!!", character: "霧島国人" },
      { title: "遊☆戯☆王VRAINS", character: "鴻上了見／リボルバー" },
      { title: "コンビニカレシ", character: "坂本真" },
      { title: "スタミュ", character: "南條聖" },
      { title: "A3!", character: "兵頭十座" },
      { title: "灼熱カバディ", character: "伊達真司" },
      { title: "KING OF PRISMシリーズ", character: "大和アレクサンダー" },
      { title: "機動戦士ガンダム ククルス・ドアンの島", character: "ククルス・ドアン" },
    ],
  },
  大地葉: {
    sourceUrl: "https://ja.wikipedia.org/wiki/大地葉",
    confirmedDate: "2026-07-14",
    works: [
      { title: "恋愛ラボ", character: "水嶋沙依理" },
      { title: "愛・天地無用！", character: "鬼ノ城紅" },
      { title: "僕だけがいない街", character: "ケンヤ" },
      { title: "ベイブレードバースト", character: "蒼井常夏" },
      { title: "つぐもも", character: "皇すなお" },
      { title: "プリンセス・プリンシパル", character: "ドロシー" },
      { title: "魔法陣グルグル", character: "ジュジュ・クー・シュナムル" },
      { title: "アイドルタイムプリパラ", character: "虹色にの" },
      { title: "ゼロから始める魔法の書", character: "アルバス" },
      { title: "かげきしょうじょ!!", character: "星野薫" },
      { title: "アズールレーン", character: "綾波" },
      { title: "フルーツバスケット", character: "草摩燈路" },
    ],
  },
  坂本真綾: {
    sourceUrl: "https://ja.wikipedia.org/wiki/坂本真綾",
    confirmedDate: "2026-07-14",
    works: [
      { title: "天空のエスカフローネ", character: "神崎ひとみ" },
      { title: "桜蘭高校ホスト部", character: "藤岡ハルヒ" },
      { title: "黒執事", character: "シエル・ファントムハイヴ" },
      { title: "機動戦士ガンダムSEED DESTINY", character: "ルナマリア・ホーク" },
      { title: "〈物語〉シリーズ", character: "忍野忍" },
      { title: "PSYCHO-PASS サイコパス", character: "王陵璃華子" },
      { title: "七つの大罪", character: "マーリン" },
      { title: "鬼滅の刃", character: "珠世" },
      { title: "荒川アンダー ザ ブリッジ", character: "ニノ" },
      { title: "四畳半神話大系", character: "明石さん" },
      { title: "フルーツバスケット", character: "草摩慊人" },
    ],
  },
  山路和弘: {
    sourceUrl: "https://dic.nicovideo.jp/a/山路和弘",
    confirmedDate: "2026-07-14",
    works: [
      { title: "名探偵コナン", character: "綾城行雄／谷口昇／北浦京吾" },
      { title: "破壊魔定光", character: "ポンコツ" },
      { title: "べるぜバブ", character: "ジャバウォック" },
      { title: "ソードアート・オンライン", character: "結城彰三" },
      { title: "PSYCHO-PASS", character: "雑賀譲二" },
      { title: "ドキドキ！プリキュア", character: "ベール" },
      { title: "戦姫絶唱シンフォギアGX", character: "風鳴八紘" },
      { title: "ワンパンマン", character: "シルバーファング" },
      { title: "ドラゴンボール超", character: "ヒット" },
      { title: "銀魂.", character: "范堺" },
      { title: "進撃の巨人", character: "ケニー・アッカーマン" },
      { title: "波よ聞いてくれ", character: "久連木克三" },
      { title: "DRAGON QUEST -ダイの大冒険-", character: "マトリフ" },
      { title: "デッドマウント・デスプレイ", character: "四乃山呂" },
    ],
  },
  野島健児: {
    sourceUrl: "https://ja.wikipedia.org/wiki/野島健児_(声優)",
    confirmedDate: "2026-07-14",
    works: [
      { title: "灼眼のシャナ", character: "佐藤啓作" },
      { title: "PSYCHO-PASS サイコパス", character: "宜野座伸元" },
      { title: "弱虫ペダル", character: "黒田雪成" },
      { title: "ハイスクールD×D", character: "木場祐斗" },
      { title: "干物妹!うまるちゃん", character: "土間タイヘイ" },
      { title: "Free!-Dive to the Future-", character: "桐嶋夏也" },
      { title: "ユーリ!!! on ICE", character: "イ・スンギル" },
      { title: "クズの本懐", character: "鐘井鳴海" },
      { title: "美少女戦士セーラームーンCrystal", character: "地場衛／タキシード仮面" },
    ],
  },
  下野紘: {
    sourceUrl: "https://ja.wikipedia.org/wiki/下野紘",
    confirmedDate: "2026-07-14",
    works: [
      { title: "ラーゼフォン", character: "神名綾人" },
      { title: "CLUSTER EDGE", character: "アゲート・フローライト" },
      { title: "ef - a fairy tale of the two.", character: "広野紘" },
      { title: "おおきく振りかぶって", character: "田島悠一郎" },
      { title: "神のみぞ知るセカイ", character: "桂木桂馬" },
      { title: "バカとテストと召喚獣", character: "吉井明久" },
      { title: "うたの☆プリンスさまっ♪", character: "来栖翔" },
      { title: "進撃の巨人", character: "コニー・スプリンガー" },
      { title: "鬼滅の刃", character: "我妻善逸" },
      { title: "弱虫ペダル", character: "鏑木一差" },
      { title: "僕のヒーローアカデミア", character: "荼毘" },
      { title: "はたらく魔王さま！", character: "漆原半蔵〈悪魔大元帥ルシフェル〉" },
    ],
  },
  小山内怜央: {
    sourceUrl: "https://ja.wikipedia.org/wiki/小山内怜央",
    confirmedDate: "2026-07-14",
    works: [
      { title: "ゲーセン少女と異文化交流", character: "草壁葵衣" },
      { title: "グロウアップショウ 〜ひまわりのサーカス団〜", character: "吾野伊万里" },
      { title: "落第賢者の学院無双", character: "アナスタシア" },
      { title: "異世界のんびり農家", character: "ロアージュ" },
      { title: "青のオーケストラ", character: "マリー" },
      { title: "マッシュル-MASHLE-", character: "マッシュ〈赤ん坊〉／アビス〈少年期〉／ドット〈幼少期〉" },
      { title: "ツンデレ悪役令嬢リーゼロッテと実況の遠藤くんと解説の小林さん", character: "レオン〈幼少期〉" },
    ],
  },
  富田美憂: {
    sourceUrl: "https://ja.wikipedia.org/wiki/富田美憂",
    confirmedDate: "2026-07-14",
    works: [
      { title: "ガヴリールドロップアウト", character: "ガヴリール／天真＝ガヴリール＝ホワイト" },
      { title: "ひなこのーと", character: "夏川くいな" },
      { title: "メイドインアビス", character: "リコ" },
      { title: "となりの吸血鬼さん", character: "ソフィー・トワイライト" },
      { title: "荒野のコトブキ飛行隊", character: "チカ" },
      { title: "ぼくたちは勉強ができない", character: "緒方理珠" },
      { title: "女子高生の無駄づかい", character: "ヤマイ／山本美波" },
      { title: "かぐや様は告らせたい", character: "伊井野ミコ" },
      { title: "ドロヘドロ", character: "恵比寿" },
      { title: "異種族レビュアーズ", character: "クリムヴェール" },
      { title: "機動戦士ガンダム 水星の魔女", character: "チュアチュリー・パンランチ" },
    ],
  },
  小原好美: {
    sourceUrl: "https://ja.wikipedia.org/wiki/小原好美",
    confirmedDate: "2026-07-14",
    works: [
      { title: "魔法陣グルグル", character: "ククリ" },
      { title: "かぐや様は告らせたい", character: "藤原千花" },
      { title: "スター☆トゥインクルプリキュア", character: "羽衣ララ／キュアミルキー" },
      { title: "あそびあそばせ", character: "野村香純" },
      { title: "まちカドまぞく", character: "吉田優子／シャミ子" },
      { title: "月がきれい", character: "水野茜" },
      { title: "ようこそ実力至上主義の教室へ", character: "橘茜" },
      { title: "からかい上手の高木さん", character: "日々野ミナ" },
      { title: "はねバド!", character: "藤沢エレナ" },
      { title: "無職転生", character: "ロキシー・ミグルディア" },
      { title: "ドメスティックな彼女", character: "葫原美雨" },
    ],
  },
  櫻井孝宏: {
    sourceUrl: "https://ja.wikipedia.org/wiki/櫻井孝宏",
    confirmedDate: "2026-07-14",
    works: [
      { title: "デジモンアドベンチャー", character: "テントモン／モチモン" },
      { title: "ゲートキーパーズ", character: "浮矢瞬" },
      { title: "コードギアス 反逆のルルーシュ", character: "枢木スザク" },
      { title: "ゼロの使い魔", character: "ギーシュ・ド・グラモン" },
      { title: "D.Gray-man", character: "神田ユウ" },
      { title: ".hack//Roots", character: "ハセヲ" },
      { title: "〈物語〉シリーズ", character: "忍野メメ" },
      { title: "モノノ怪", character: "薬売り" },
      { title: "PSYCHO-PASS", character: "槙島聖護／雛河翔" },
      { title: "鬼滅の刃", character: "冨岡義勇" },
      { title: "おそ松さん", character: "松野おそ松" },
      { title: "呪術廻戦", character: "夏油傑" },
      { title: "ダイヤのA", character: "御幸一也" },
      { title: "響け!ユーフォニアム", character: "滝昇" },
      { title: "転生したらスライムだった件", character: "ディアブロ" },
    ],
  },
  長谷川育美: {
    sourceUrl: "https://ja.wikipedia.org/wiki/長谷川育美",
    confirmedDate: "2026-07-14",
    works: [
      { title: "86-エイティシックス-", character: "ヴラディレーナ・ミリーゼ" },
      { title: "弱キャラ友崎くん", character: "七海みなみ" },
      { title: "ウマ娘 プリティーダービー", character: "ミホノブルボン" },
      { title: "現実主義勇者の王国再建記", character: "アイーシャ・ウドガルド" },
      { title: "恋は世界征服のあとで", character: "禍原デス美（死神王女）" },
      { title: "ぼっち・ざ・ろっく！", character: "喜多郁代" },
      { title: "ワールドダイスター", character: "静香" },
      { title: "私の推しは悪役令嬢。", character: "レーネ＝オルソー" },
      { title: "推しが武道館いってくれたら死ぬ", character: "松山空音" },
      { title: "異種族レビュアーズ", character: "エルシャ" },
    ],
  },
  市ノ瀬加那: {
    sourceUrl: "https://ja.wikipedia.org/wiki/市ノ瀬加那",
    confirmedDate: "2026-07-14",
    works: [
      { title: "ダーリン・イン・ザ・フランキス", character: "イチゴ" },
      { title: "色づく世界の明日から", character: "風野あさぎ" },
      { title: "Fairy gone フェアリーゴーン", character: "マーリヤ・ノエル" },
      { title: "キャロル&チューズデイ", character: "チューズデイ" },
      { title: "ひとりぼっちの○○生活", character: "倉井佳子" },
      { title: "Dr.STONE", character: "小川杠" },
      { title: "機動戦士ガンダム 水星の魔女", character: "スレッタ・マーキュリー" },
      { title: "ひげを剃る。そして女子高生を拾う。", character: "荻原沙優" },
      { title: "聖女の魔力は万能です", character: "アイラ（御園愛良）" },
      { title: "葬送のフリーレン", character: "フェルン" },
      { title: "あやかしトライアングル", character: "花奏すず" },
    ],
  },
  内田雄馬: {
    sourceUrl: "https://ja.wikipedia.org/wiki/内田雄馬",
    confirmedDate: "2026-07-14",
    works: [
      { title: "呪術廻戦", character: "伏黒恵" },
      { title: "BANANA FISH", character: "アッシュ・リンクス" },
      { title: "マクロスΔ", character: "ハヤテ・インメルマン" },
      { title: "ガンダムビルドファイターズトライ", character: "コウサカ・ユウマ" },
      { title: "ReLIFE", character: "大神和臣" },
      { title: "りゅうおうのおしごと!", character: "九頭竜八一" },
      { title: "フルーツバスケット", character: "草摩夾" },
      { title: "ギヴン", character: "上ノ山立夏" },
      { title: "地縛少年花子くん", character: "源輝" },
      { title: "BORUTO", character: "カワキ" },
      { title: "ぐらんぶる", character: "北原伊織" },
      { title: "アイドルマスター SideM", character: "桜庭薫" },
    ],
  },
  木村良平: {
    sourceUrl: "https://ja.wikipedia.org/wiki/木村良平",
    confirmedDate: "2026-07-14",
    works: [
      { title: "東のエデン", character: "滝沢朗" },
      { title: "黒子のバスケ", character: "黄瀬涼太" },
      { title: "テイルズ オブ ゼスティリア", character: "スレイ" },
      { title: "夏目友人帳", character: "西村悟" },
      { title: "銀の匙 Silver Spoon", character: "八軒勇吾" },
      { title: "僕は友達が少ない", character: "羽瀬川小鷹" },
      { title: "輪るピングドラム", character: "高倉晶馬" },
      { title: "坂道のアポロン", character: "西見薫" },
      { title: "Angel Beats!", character: "日向秀樹" },
      { title: "神様ドォルズ", character: "枸雅阿幾" },
      { title: "魔入りました!入間くん", character: "アスモデウス・アリス" },
      { title: "ハイキュー!!", character: "木兎光太郎" },
    ],
  },
  小西克幸: {
    sourceUrl: "https://ja.wikipedia.org/wiki/小西克幸",
    confirmedDate: "2026-07-14",
    works: [
      { title: "勇者王ガオガイガー", character: "ボルフォッグ／ビッグボルフォッグ" },
      { title: "妖しのセレス", character: "十夜" },
      { title: "魔法戦士リウイ", character: "リウイ" },
      { title: "シャーマンキング", character: "阿弥陀丸" },
      { title: "SAMURAI DEEPER KYO", character: "鬼眼の狂／壬生京四郎" },
      { title: "金色のコルダ", character: "王崎信武" },
      { title: "天元突破グレンラガン", character: "カミナ" },
      { title: "マクロスF", character: "オズマ・リー" },
      { title: "D.Gray-man", character: "コムイ・リー" },
      { title: "FAIRY TAIL", character: "ラクサス・ドレアー／ユーリ・ドレアー" },
      { title: "ジョジョの奇妙な冒険 黄金の風", character: "ボス／ディアボロ" },
      { title: "鬼滅の刃", character: "宇髄天元" },
      { title: "ブラッククローバー", character: "フエゴレオン・ヴァーミリオン" },
    ],
  },
  熊谷健太郎: {
    sourceUrl: "https://ja.wikipedia.org/wiki/熊谷健太郎",
    confirmedDate: "2026-07-14",
    works: [
      { title: "徒然チルドレン", character: "高瀬春彦" },
      { title: "グランクレスト戦記", character: "テオ・コルネーロ" },
      { title: "はたらく細胞", character: "白血球〈4989〉" },
      { title: "火ノ丸相撲", character: "五條佑真" },
      { title: "アイドルマスター SideM", character: "握野英雄" },
      { title: "A3!", character: "伏見臣" },
      { title: "GETUP! GETLIVE! #げらげら", character: "狛江一馬" },
      { title: "池袋ウエストゲートパーク", character: "真島マコト" },
      { title: "number24", character: "染谷誠" },
      { title: "ダンジョン飯", character: "ライオス" },
      { title: "この世界は不完全すぎる", character: "黒崎優（クロちゃん）" },
      { title: "多数欠", character: "相馬隼人" },
    ],
  },
  大塚剛央: {
    sourceUrl: "https://ja.wikipedia.org/wiki/大塚剛央",
    confirmedDate: "2026-07-14",
    works: [
      { title: "風が強く吹いている", character: "蔵原走（カケル）" },
      { title: "【推しの子】", character: "アクア" },
      { title: "薬屋のひとりごと", character: "壬氏" },
      { title: "機動戦士ガンダム 水星の魔女", character: "ラウダ・ニール" },
      { title: "もののがたり", character: "岐兵馬" },
      { title: "ゆびさきと恋々", character: "芦沖桜志" },
      { title: "忘却バッテリー", character: "国都英一郎" },
      { title: "トリリオンゲーム", character: "天王寺陽" },
      { title: "ハイガクラ", character: "一葉" },
      { title: "百千さん家のあやかし王子", character: "七守葵／鵺" },
    ],
  },
  土岐隼一: {
    sourceUrl: "https://ja.wikipedia.org/wiki/土岐隼一",
    confirmedDate: "2026-07-14",
    works: [
      { title: "かくりよの宿飯", character: "銀次" },
      { title: "地縛少年花子くん", character: "蒼井茜" },
      { title: "A3!", character: "瑠璃川幸" },
      { title: "モンスター娘のお医者さん", character: "グレン・リトバイト" },
      { title: "キミと僕の最後の戦場、あるいは世界が始まる聖戦", character: "ジン・シュラルガン" },
      { title: "WAVE!!〜サーフィンやっぺ!!〜", character: "木戸ナオヤ" },
      { title: "東京リベンジャーズ", character: "羽宮一虎" },
      { title: "TSUKIPRO THE ANIMATION", character: "衛藤昂輝" },
    ],
  },
  若山詩音: {
    sourceUrl: "https://ja.wikipedia.org/wiki/若山詩音",
    confirmedDate: "2026-07-14",
    works: [
      { title: "SSSS.DYNAZENON", character: "南夢芽" },
      { title: "さよなら私のクラマー", character: "越前佐和" },
      { title: "takt op.Destiny", character: "運命／コゼット・シュナイダー" },
      { title: "ハコヅメ〜交番女子の逆襲〜", character: "川合麻依" },
      { title: "明日ちゃんのセーラー服", character: "古城智乃" },
      { title: "リコリス・リコイル", character: "井ノ上たきな" },
      { title: "無職転生 〜異世界行ったら本気だす〜", character: "ナナホシ" },
      { title: "好きな子がめがねを忘れた", character: "三重あい" },
      { title: "ダンダダン", character: "モモ（綾瀬桃）" },
    ],
  },
  稗田寧々: {
    sourceUrl: "https://ja.wikipedia.org/wiki/稗田寧々",
    confirmedDate: "2026-07-14",
    works: [
      { title: "ガンダムビルドダイバーズ", character: "ヤシロ・モモカ" },
      { title: "魔王学院の不適合者", character: "ミサ・イリオローグ" },
      { title: "戦翼のシグルドリーヴァ", character: "六車・宮古" },
      { title: "弱キャラ友崎くん", character: "泉優鈴" },
      { title: "骸骨騎士様、只今異世界へお出掛け中", character: "ポンタ" },
      { title: "CUE!", character: "鷹取舞花" },
      { title: "恋は世界征服のあとで", character: "神宮寺美咲" },
      { title: "もういっぽん!", character: "南雲安奈" },
      { title: "最強陰陽師の異世界転生記", character: "アミュ" },
      { title: "Summer Pockets", character: "久島鴎" },
      { title: "クラスの大嫌いな女子と結婚することになった。", character: "北条糸青" },
    ],
  },
  竹内良太: {
    sourceUrl: "https://ja.wikipedia.org/wiki/竹内良太",
    confirmedDate: "2026-07-14",
    works: [
      { title: "ハイキュー!!", character: "牛島若利" },
      { title: "魔法使いの嫁", character: "エリアス・エインズワース" },
      { title: "青の祓魔師", character: "経堂直哉" },
      { title: "DRAMAtical Murder", character: "蓮" },
      { title: "ID:INVADED", character: "名探偵 穴井戸／富久田保津" },
      { title: "天地創造デザイン部", character: "海原" },
      { title: "組長娘と世話係", character: "桜樹一彦" },
      { title: "骸骨騎士様、只今異世界へお出掛け中", character: "ゴエモン" },
      { title: "火ノ丸相撲", character: "天王寺獅童" },
      { title: "来世は他人がいい", character: "橘葵" },
      { title: "青のミブロ", character: "芹沢鴨" },
    ],
  },
  杉田智和: {
    sourceUrl: "https://ja.wikipedia.org/wiki/杉田智和",
    confirmedDate: "2026-07-14",
    works: [
      { title: "銀魂", character: "坂田銀時" },
      { title: "涼宮ハルヒの憂鬱", character: "キョン" },
      { title: "ジョジョの奇妙な冒険", character: "ジョセフ・ジョースター" },
      { title: "ちょびっツ", character: "本須和秀樹" },
      { title: "創聖のアクエリオン", character: "シリウス・ド・アリシア" },
      { title: "SHUFFLE!", character: "土見稟" },
      { title: "ハチミツとクローバー", character: "真山巧" },
      { title: "食戟のソーマ", character: "叡山枝津也" },
      { title: "戦姫絶唱シンフォギア", character: "ウェル博士" },
      { title: "翠星のガルガンティア", character: "チェインバー" },
      { title: "鬼滅の刃", character: "悲鳴嶼行冥" },
      { title: "ゴールデンカムイ", character: "二階堂浩平" },
      { title: "七つの大罪", character: "エスカノール" },
    ],
  },
  加藤英美里: {
    sourceUrl: "https://ja.wikipedia.org/wiki/加藤英美里",
    confirmedDate: "2026-07-14",
    works: [
      { title: "らき☆すた", character: "柊かがみ" },
      { title: "出ましたっ!パワパフガールズZ", character: "赤堤ももこ／ハイパー・ブロッサム" },
      { title: "黒執事", character: "メイリン" },
      { title: "〈物語〉シリーズ", character: "八九寺真宵" },
      { title: "ゆるゆり", character: "大室櫻子" },
      { title: "オーバーロード", character: "アウラ・ベラ・フィオーラ" },
      { title: "小林さんちのメイドラゴン", character: "才川リコ" },
      { title: "SPY×FAMILY", character: "ベッキー・ブラックベル" },
      { title: "バカとテストと召喚獣", character: "木下秀吉／木下優子" },
      { title: "魔法少女まどか☆マギカ", character: "キュゥべえ" },
      { title: "ログ・ホライズン", character: "アカツキ" },
    ],
  },
  畠中祐: {
    sourceUrl: "https://ja.wikipedia.org/wiki/畠中祐",
    confirmedDate: "2026-07-14",
    works: [
      { title: "遊☆戯☆王ZEXAL", character: "九十九遊馬" },
      { title: "うしおととら", character: "蒼月潮" },
      { title: "甲鉄城のカバネリ", character: "生駒" },
      { title: "僕のヒーローアカデミア", character: "上鳴電気" },
      { title: "東京リベンジャーズ", character: "柴八戒" },
      { title: "SK∞ エスケーエイト", character: "喜屋武暦" },
      { title: "ましろのおと", character: "田沼総一" },
      { title: "MARS RED", character: "栗栖秀太郎" },
      { title: "プレイタの傷", character: "虎尊イツキ" },
      { title: "ゴールデンカムイ", character: "花沢勇作" },
      { title: "ダイヤのA", character: "浅田浩文" },
    ],
  },
  種﨑敦美: {
    sourceUrl: "https://ja.wikipedia.org/wiki/種﨑敦美",
    confirmedDate: "2026-07-14",
    works: [
      { title: "SPY×FAMILY", character: "アーニャ・フォージャー" },
      { title: "ドラゴンクエスト ダイの大冒険", character: "ダイ" },
      { title: "葬送のフリーレン", character: "フリーレン" },
      { title: "魔法使いの嫁", character: "羽鳥チセ" },
      { title: "響け！ユーフォニアム", character: "鎧塚みぞれ" },
      { title: "Vivy -Fluorite Eye's Song-", character: "ヴィヴィ／ディーバ" },
      { title: "その着せ替え人形は恋をする", character: "乾紗寿叶" },
      { title: "わんだふるぷりきゅあ!", character: "犬飼いろは／キュアフレンディ" },
    ],
  },
  芹澤優: {
    sourceUrl: "https://ja.wikipedia.org/wiki/芹澤優",
    confirmedDate: "2026-07-14",
    works: [
      { title: "プリティーリズム・レインボーライブ", character: "福原あん" },
      { title: "ムシブギョー", character: "一乃谷天間" },
      { title: "犬とハサミは使いよう", character: "秋月マキシ" },
      { title: "プリパラ", character: "南みれぃ" },
      { title: "実は私は", character: "白神葉子" },
      { title: "俺がお嬢様学校に「庶民サンプル」としてゲッツされた件", character: "天空橋愛佳" },
      { title: "双星の陰陽師", character: "音海繭良" },
      { title: "賭ケグルイ", character: "夢見弖ユメミ" },
      { title: "3D彼女 リアルガール", character: "五十嵐色葉" },
      { title: "キラッとプリ☆チャン", character: "赤城あんな" },
      { title: "トニカクカワイイ", character: "有栖川要" },
      { title: "彼女、お借りします", character: "八重森みに" },
      { title: "てんぷる", character: "蒼葉月夜" },
    ],
  },
  黒沢ともよ: {
    sourceUrl: "https://ja.wikipedia.org/wiki/黒沢ともよ",
    confirmedDate: "2026-07-14",
    works: [
      { title: "アイカツ!", character: "有栖川おとめ" },
      { title: "ブラック・ブレット", character: "ティナ・スプラウト" },
      { title: "甘城ブリリアントパーク", character: "シルフィー" },
      { title: "結城友奈は勇者である", character: "犬吠埼樹" },
      { title: "アイドルマスター シンデレラガールズ", character: "赤城みりあ" },
      { title: "響け!ユーフォニアム", character: "黄前久美子" },
      { title: "宝石の国", character: "フォスフォフィライト" },
      { title: "BanG Dream!", character: "ミッシェル／奥沢美咲" },
      { title: "ゆるキャン△", character: "土岐綾乃" },
      { title: "アークナイツ", character: "アーミヤ" },
    ],
  },
  くじら: {
    sourceUrl: "https://ja.wikipedia.org/wiki/くじら_(声優)",
    confirmedDate: "2026-07-14",
    works: [
      { title: "NARUTO -ナルト-", character: "大蛇丸" },
      { title: "銀魂", character: "お登勢" },
      { title: "おそ松さん", character: "松野松代（母さん）" },
      { title: "ダンガンロンパ", character: "大神さくら" },
      { title: "妖しのセレス", character: "小田玖" },
      { title: "ソニックX", character: "エラ" },
      { title: "ドッとKONIちゃん", character: "KONI" },
      { title: "無職転生", character: "ヒトガミ" },
      { title: "百姓貴族", character: "おかん" },
    ],
  },
  古賀葵: {
    sourceUrl: "https://ja.wikipedia.org/wiki/古賀葵",
    confirmedDate: "2026-07-14",
    works: [
      { title: "魔法少女？なりあ☆がーるず", character: "はなび" },
      { title: "天使の3P!", character: "金城そら" },
      { title: "つうかあ", character: "宮田ゆり" },
      { title: "かぐや様は告らせたい〜天才たちの恋愛頭脳戦〜", character: "四宮かぐや" },
      { title: "慎重勇者〜この勇者が俺TUEEEくせに慎重すぎる〜", character: "エルル" },
      { title: "究極進化したフルダイブRPGが現実よりもクソゲーだったら", character: "結城楓" },
      { title: "異世界魔王と召喚少女の奴隷魔術Ω", character: "ロゼ" },
      { title: "ぼくたちのリメイク", character: "志野亜貴" },
      { title: "古見さんは、コミュ症です。", character: "古見硝子" },
      { title: "先輩がうざい後輩の話", character: "月城モナ" },
      { title: "ホリミヤ", character: "奥山有菜" },
      { title: "ひろがるスカイ!プリキュア", character: "エルちゃん／キュアマジェスティ" },
    ],
  },
  福山潤: {
    sourceUrl: "https://ja.wikipedia.org/wiki/福山潤",
    confirmedDate: "2026-07-14",
    works: [
      { title: "コードギアス 反逆のルルーシュ", character: "ルルーシュ・ランペルージ" },
      { title: "暗殺教室", character: "殺せんせー" },
      { title: "おそ松さん", character: "一松" },
      { title: "黒執事", character: "グレル・サトクリフ" },
      { title: "デュラララ!!", character: "岸谷新羅" },
      { title: "キングダム", character: "嬴政" },
      { title: "七つの大罪", character: "キング" },
      { title: "WORKING!!", character: "小鳥遊宗太" },
      { title: "狼と香辛料", character: "クラフト・ロレンス" },
      { title: "ぬらりひょんの孫", character: "奴良リクオ" },
      { title: "青の祓魔師", character: "奥村雪男" },
      { title: "ブラッククローバー", character: "フィンラル・ルーラケイス" },
      { title: "弱虫ペダル", character: "岸神小鞠" },
    ],
  },
  松岡禎丞: {
    sourceUrl: "https://ja.wikipedia.org/wiki/松岡禎丞",
    confirmedDate: "2026-07-14",
    works: [
      { title: "ソードアート・オンライン", character: "キリト／桐ヶ谷和人" },
      { title: "神様のメモ帳", character: "藤島鳴海" },
      { title: "ダンジョンに出会いを求めるのは間違っているだろうか", character: "ベル・クラネル" },
      { title: "食戟のソーマ", character: "幸平創真" },
      { title: "五等分の花嫁", character: "上杉風太郎" },
      { title: "鬼滅の刃", character: "嘴平伊之助" },
      { title: "Re:ゼロから始める異世界生活", character: "ペテルギウス・ロマネコンティ" },
      { title: "弱虫ペダル", character: "青八木一" },
      { title: "モブサイコ100", character: "花沢輝気" },
      { title: "リコリス・リコイル", character: "真島" },
      { title: "TRIGUN STAMPEDE", character: "ヴァッシュ・ザ・スタンピード" },
    ],
  },
  田丸篤志: {
    sourceUrl: "https://ja.wikipedia.org/wiki/田丸篤志",
    confirmedDate: "2026-07-14",
    works: [
      { title: "たまこまーけっと", character: "大路もち蔵" },
      { title: "ハイキュー!!", character: "国見英" },
      { title: "魔法科高校の劣等生", character: "吉田幹比古" },
      { title: "学戦都市アスタリスク", character: "天霧綾斗" },
      { title: "俺がお嬢様学校に「庶民サンプル」としてゲッツされた件", character: "神楽坂公人" },
      { title: "刀剣乱舞-花丸-", character: "一期一振" },
      { title: "かくりよの宿飯", character: "白夜" },
      { title: "A3!", character: "月岡紬" },
      { title: "アイ★チュウ", character: "鳶倉アキヲ" },
    ],
  },
  岡本信彦: {
    sourceUrl: "https://ja.wikipedia.org/wiki/岡本信彦",
    confirmedDate: "2026-07-14",
    works: [
      { title: "ゴーストハント", character: "ジョン・ブラウン" },
      { title: "sola", character: "森宮依人" },
      { title: "とある魔術の禁書目録シリーズ", character: "一方通行〈アクセラレータ〉" },
      { title: "明日のよいち!", character: "烏丸与一" },
      { title: "鋼殻のレギオス", character: "レイフォン・アルセイフ" },
      { title: "バクマン。", character: "新妻エイジ" },
      { title: "青の祓魔師シリーズ", character: "奥村燐" },
      { title: "僕のヒーローアカデミアシリーズ", character: "爆豪勝己" },
      { title: "ハイキュー!!シリーズ", character: "西谷夕" },
      { title: "鬼滅の刃シリーズ", character: "不死川玄弥" },
      { title: "葬送のフリーレン", character: "ヒンメル" },
      { title: "Re:ゼロから始める異世界生活", character: "ガーフィール" },
    ],
  },
  千葉翔也: {
    sourceUrl: "https://ja.wikipedia.org/wiki/千葉翔也",
    confirmedDate: "2026-07-14",
    works: [
      { title: "ようこそ実力至上主義の教室へ", character: "綾小路清隆" },
      { title: "月がきれい", character: "安曇小太郎" },
      { title: "はたらく細胞", character: "B細胞" },
      { title: "どろろ", character: "多宝丸" },
      { title: "地縛少年花子くん", character: "源光" },
      { title: "86-エイティシックス-", character: "シンエイ・ノウゼン" },
      { title: "青のオーケストラ", character: "青野一" },
      { title: "WIND BREAKER", character: "楡井秋彦" },
      { title: "アイドルマスター SideM", character: "秋山隼人" },
      { title: "B-PROJECT", character: "不動明謙" },
      { title: "パリピ孔明", character: "KABE太人" },
      { title: "ブルーロック", character: "今村遊大" },
    ],
  },
  甲斐田裕子: {
    sourceUrl: "https://ja.wikipedia.org/wiki/甲斐田裕子",
    confirmedDate: "2026-07-14",
    works: [
      { title: "ジーンシャフト", character: "ソフィア・ガルガリン" },
      { title: "一騎当千", character: "呂蒙子明" },
      { title: "銀魂", character: "月詠" },
      { title: "とある魔術の禁書目録", character: "黄泉川愛穂" },
      { title: "咲-Saki-", character: "井上純" },
      { title: "戦国BASARA", character: "まつ" },
      { title: "約束のネバーランド", character: "イザベラ" },
      { title: "SPY×FAMILY", character: "シルヴィア・シャーウッド" },
      { title: "とらドラ!", character: "狩野すみれ" },
      { title: "怪物王女", character: "リザ" },
    ],
  },
  八代拓: {
    sourceUrl: "https://ja.wikipedia.org/wiki/八代拓",
    confirmedDate: "2026-07-14",
    works: [
      { title: "タイガーマスクW", character: "東ナオト／タイガーマスク" },
      { title: "アイカツスターズ!", character: "結城すばる" },
      { title: "この男子、魔法がお仕事です。", character: "内海十四日" },
      { title: "迷家-マヨイガ-", character: "颯人" },
      { title: "アイドルマスター SideM", character: "柏木翼" },
      { title: "ガンダムビルドダイバーズ", character: "シバ・ツカサ" },
      { title: "千銃士", character: "ブラウン・ベス" },
      { title: "KING OF PRISM -Shiny Seven Stars-", character: "十王院カケル" },
      { title: "あひるの空", character: "安原真一" },
      { title: "炎炎ノ消防隊", character: "ヴァルカン・ジョゼフ" },
      { title: "ドメスティックな彼女", character: "藤井夏生" },
      { title: "転生したらスライムだった件", character: "イフリート" },
      { title: "かくしごと", character: "志治仰" },
      { title: "るろうに剣心 -明治剣客浪漫譚-", character: "相楽左之助" },
    ],
  },
  上坂すみれ: {
    sourceUrl: "https://ja.wikipedia.org/wiki/上坂すみれ",
    confirmedDate: "2026-07-14",
    works: [
      { title: "中二病でも恋がしたい！", character: "凸守早苗" },
      { title: "ガールズ&パンツァー", character: "ノンナ／ぴよたん" },
      { title: "アイドルマスター シンデレラガールズ", character: "アナスタシア" },
      { title: "オーバーロード", character: "シャルティア・ブラッドフォールン" },
      { title: "艦隊これくしょん -艦これ-", character: "吹雪" },
      { title: "スター☆トゥインクルプリキュア", character: "キュアコスモ／ユニ" },
      { title: "BanG Dream!", character: "白鷺千聖" },
      { title: "イジらないで、長瀞さん", character: "長瀞さん" },
      { title: "うる星やつら (2022)", character: "ラム" },
      { title: "時々ボソッとロシア語でデレる隣のアーリャさん", character: "アーリャ" },
    ],
  },
  中村カンナ: {
    sourceUrl: "https://ja.wikipedia.org/wiki/中村カンナ",
    confirmedDate: "2026-07-14",
    works: [
      { title: "それでも歩は寄せてくる", character: "八乙女うるし" },
      { title: "白聖女と黒牧師", character: "ヘーゼリッタ" },
      { title: "英雄教室", character: "アン" },
      { title: "七つの大罪 黙示録の四騎士", character: "アン" },
      { title: "神は遊戯に飢えている。", character: "ネル・レックレス" },
      { title: "歴史に残る悪女になるぞ", character: "ウィリアムズ・アリシア" },
      { title: "ウマ娘 プリティーダービー", character: "ナリタトップロード" },
      { title: "わたしが恋人になれるわけないじゃん、ムリムリ!", character: "甘織れな子" },
    ],
  },
  井口裕香: {
    sourceUrl: "https://ja.wikipedia.org/wiki/井口裕香",
    confirmedDate: "2026-07-14",
    works: [
      { title: "アイドルマスター XENOGLOSSIA", character: "天海春香" },
      { title: "true tears", character: "安藤愛子" },
      { title: "とある魔術の禁書目録", character: "インデックス" },
      { title: "仮面のメイドガイ", character: "富士原なえか" },
      { title: "僕は友達が少ない", character: "高山マリア" },
      { title: "まよチキ！", character: "近衛スバル" },
      { title: "ロウきゅーぶ！", character: "三沢真帆" },
      { title: "ガールズ&パンツァー", character: "冷泉麻子" },
      { title: "戦姫絶唱シンフォギア", character: "小日向未来" },
      { title: "ヤマノススメ", character: "雪村あおい" },
      { title: "ダンジョンに出会いを求めるのは間違っているだろうか", character: "ヒタチ・千草" },
      { title: "本好きの下剋上", character: "マイン／ローゼマイン" },
      { title: "デリシャスパーティ♡プリキュア", character: "華満らん／キュアヤムヤム" },
    ],
  },
  細谷佳正: {
    sourceUrl: "https://ja.wikipedia.org/wiki/細谷佳正",
    confirmedDate: "2026-07-14",
    works: [
      { title: "刀語", character: "鑢七花" },
      { title: "会長はメイド様!", character: "黒崎龍之介" },
      { title: "レベルE", character: "筒井雪隆" },
      { title: "NO.6", character: "ネズミ" },
      { title: "ちはやふる", character: "綿谷新" },
      { title: "黒子のバスケ", character: "日向順平" },
      { title: "新テニスの王子様", character: "白石蔵ノ介" },
      { title: "進撃の巨人", character: "ライナー・ブラウン" },
      { title: "キングダム", character: "王賁" },
      { title: "ストライク・ザ・ブラッド", character: "暁古城" },
      { title: "ハイキュー!!", character: "東峰旭" },
      { title: "Free!", character: "山崎宗介" },
      { title: "文豪ストレイドッグス", character: "国木田独歩" },
      { title: "ゴールデンカムイ", character: "谷垣源次郎" },
      { title: "この世界の片隅に", character: "北條周作" },
    ],
  },
  新谷真弓: {
    sourceUrl: "https://ja.wikipedia.org/wiki/新谷真弓",
    confirmedDate: "2026-07-14",
    works: [
      { title: "彼氏彼女の事情", character: "芝姫つばさ" },
      { title: "地球少女アルジュナ", character: "シンディ・クライン" },
      { title: "キルラキル", character: "蛇崩乃音" },
      { title: "黒執事 Book of Circus", character: "ウェンディ" },
      { title: "宇宙パトロールルル子", character: "ミドリ" },
      { title: "フリクリ", character: "ハルハラ・ハル子" },
      { title: "出会って5秒でバトル", character: "魅音" },
    ],
  },
  青木瑠璃子: {
    sourceUrl: "https://ja.wikipedia.org/wiki/青木瑠璃子",
    confirmedDate: "2026-07-14",
    works: [
      { title: "アイドルマスター シンデレラガールズ", character: "多田李衣菜" },
      { title: "ウマ娘 プリティーダービー", character: "エアグルーヴ" },
      { title: "クロスアンジュ 天使と竜の輪舞", character: "ノンナ" },
      { title: "アイドルメモリーズ", character: "羅雨照" },
      { title: "ROBOMASTERS THE ANIMATED SERIES", character: "カトリーナ" },
      { title: "マブラヴ オルタネイティヴ", character: "香月夕呼" },
      { title: "古見さんは、コミュ症です。", character: "尾根峰ねね" },
      { title: "盾の勇者の成り上がり", character: "エクレール" },
      { title: "便利屋斎藤さん、異世界に行く", character: "フランリル" },
      { title: "女神のカフェテラス", character: "幕澤桜花" },
      { title: "青のオーケストラ", character: "高橋翼" },
    ],
  },
  戸谷菊之介: {
    sourceUrl: "https://ja.wikipedia.org/wiki/戸谷菊之介",
    confirmedDate: "2026-07-14",
    works: [
      { title: "チェンソーマン", character: "デンジ" },
      { title: "UniteUp!", character: "清瀬明良" },
      { title: "柚木さんちの四兄弟。", character: "柚木尊" },
      { title: "七つの大罪 黙示録の四騎士", character: "ドニー" },
      { title: "逃げ上手の若君", character: "吹雪" },
      { title: "黒執事 -寄宿学校編-", character: "チェスロック" },
      { title: "魔法科高校の劣等生", character: "九島光宣" },
    ],
  },
  梶裕貴: {
    sourceUrl: "https://ja.wikipedia.org/wiki/梶裕貴",
    confirmedDate: "2026-07-14",
    works: [
      { title: "進撃の巨人", character: "エレン・イェーガー" },
      { title: "マギ", character: "アリババ・サルージャ" },
      { title: "七つの大罪", character: "メリオダス" },
      { title: "クラシカロイド", character: "モーツァルト" },
      { title: "Occultic;Nine", character: "我聞悠太" },
      { title: "僕のヒーローアカデミア", character: "轟焦凍" },
      { title: "アクセル・ワールド", character: "ハルユキ（有田春雪）" },
      { title: "ギルティクラウン", character: "桜満集" },
      { title: "ハイキュー!!", character: "孤爪研磨" },
      { title: "黒執事", character: "フィニアン" },
      { title: "ポケットモンスター XY", character: "シトロン" },
    ],
  },
  花澤香菜: {
    sourceUrl: "https://ja.wikipedia.org/wiki/花澤香菜",
    confirmedDate: "2026-07-14",
    works: [
      { title: "ゼーガペイン", character: "カミナギ・リョーコ" },
      { title: "To LOVEる -とらぶる-", character: "結城美柑" },
      { title: "〈物語〉シリーズ", character: "千石撫子" },
      { title: "Angel Beats!", character: "天使／立華かなで" },
      { title: "STEINS;GATE", character: "椎名まゆり" },
      { title: "PSYCHO-PASS サイコパス", character: "常守朱" },
      { title: "俺の妹がこんなに可愛いわけがない", character: "黒猫" },
      { title: "デュラララ!!", character: "園原杏里" },
      { title: "僕は友達が少ない", character: "羽瀬川小鳩" },
      { title: "五等分の花嫁", character: "中野一花" },
      { title: "鬼滅の刃", character: "甘露寺蜜璃" },
      { title: "はたらく細胞", character: "赤血球" },
    ],
  },
  森川智之: {
    sourceUrl: "https://ja.wikipedia.org/wiki/森川智之",
    confirmedDate: "2026-07-14",
    works: [
      { title: "宇宙の騎士テッカマンブレード", character: "Dボウイ" },
      { title: "SLAM DUNK", character: "水戸洋平" },
      { title: "剣風伝奇ベルセルク", character: "グリフィス" },
      { title: "金田一少年の事件簿", character: "明智健悟" },
      { title: "犬夜叉", character: "奈落" },
      { title: "戦国BASARA", character: "片倉小十郎" },
      { title: "クレヨンしんちゃん", character: "野原ひろし（2代目）" },
      { title: "鬼滅の刃", character: "産屋敷耀哉" },
      { title: "ブラッククローバー", character: "ユリウス・ノヴァクロノ" },
      { title: "フルーツバスケット", character: "草摩藉真" },
    ],
  },
};
